/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 09:51:13 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Clock;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.function.BiFunction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Gestor_Artigos_ESTest extends Gestor_Artigos_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      LocalDate localDate0 = MockLocalDate.now();
      String string0 = "V:7slKY7iU";
      linkedHashSet0.add("V:7slKY7iU");
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("V:7slKY7iU");
      // Undeclared exception!
      try { 
        gestor_Artigos0.vendaTotal(linkedHashSet0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(907);
      Long long1 = new Long((-1742L));
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(0);
      Boolean boolean0 = new Boolean(false);
      Boolean.logicalOr(true, false);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      Boolean boolean1 = Boolean.TRUE;
      Gestor_Artigos.setTaxaNovo((-1324.72546));
      gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean1);
      Gestor_Artigos.getTaxaNovo();
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      gestor_Artigos0.pesquisar_artigos_marca_mala("-MT`9%-)Va$&hsT");
      // Undeclared exception!
      try { 
        gestor_Artigos0.artigoToString(" Ano da Cole\u00E7\u00E3o: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(907);
      gestor_Artigos0.criar_artigo_sapatilhas("palmeiras", "v\"^Nu(VO.Z:", 0.0, true, 0, 907, long0, 0L, 0, false, "@U.Qv`EO$VY-?s!", 838, true, 10.0);
      Long long1 = new Long((-1742L));
      Long.getLong("nl31<EPa,&>CvX");
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.pesquisar_artigos_cor("nl31<EPa,&>CvX");
      gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(0);
      Boolean boolean0 = new Boolean(false);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      Boolean boolean1 = Boolean.TRUE;
      gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean1);
      Gestor_Artigos.getTaxaNovo();
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      gestor_Artigos0.pesquisar_artigos_marca_mala("-MT`9%-)Va$&hsT");
      // Undeclared exception!
      try { 
        gestor_Artigos0.artigoToString(" Ano da Cole\u00E7\u00E3o: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(0);
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o:  Marca:  Pre\u00E7o base: -1248.303 Novo: false Estado de uso: 0 N\u00FAmero de utilizadores: 0 Disponivel: true Id da transportadora: 1328 Id do vendedor: 1328 } Dimens\u00E3o: 0 Material: bIW?W@u^~.sL1 Ano da Cole\u00E7\u00E3o: 4428 Premium: false Valoriza\u00E7\u00E3o: 1328.0}\n", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2031), 5, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 5, false, 1368);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Long.getLong("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o:  Marca:  Pre\u00E7o base: -1248.303 Novo: false Estado de uso: 0 N\u00FAmero de utilizadores: 0 Disponivel: true Id da transportadora: 1328 Id do vendedor: 1328 } Dimens\u00E3o: 0 Material: bIW?W@u^~.sL1 Ano da Cole\u00E7\u00E3o: 4428 Premium: false Valoriza\u00E7\u00E3o: 1328.0}\n", (Long) null);
      Tamanho tamanho0 = Tamanho.XL;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("oEQ$omS=l_-", "Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o:  Marca:  Pre\u00E7o base: -1248.303 Novo: false Estado de uso: 0 N\u00FAmero de utilizadores: 0 Disponivel: true Id da transportadora: 1328 Id do vendedor: 1328 } Dimens\u00E3o: 0 Material: bIW?W@u^~.sL1 Ano da Cole\u00E7\u00E3o: 4428 Premium: false Valoriza\u00E7\u00E3o: 1328.0}\n", 0.0, false, 1813, 4428, 1813, long0, tamanho0, padrao0);
      Tamanho tamanho1 = Tamanho.S;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho1);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("y}d1sW");
      gestor_Artigos0.pesquisar_artigos_material((String) null);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2339));
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2030), 5, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 5, false, 1368);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Long.getLong("", (Long) null);
      Long long1 = new Long((-2916L));
      Long.getLong("A1", long1);
      Tamanho tamanho0 = Tamanho.S;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("oEQ$omS=l_-", "", 0.0, false, 1813, 4428, 1813, long0, tamanho0, padrao0);
      Tamanho tamanho1 = Tamanho.S;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho1);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("y}d1sW");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Encomenda encomenda0 = new Encomenda();
      gestor_Artigos0.alteraData(encomenda0);
      Map<String, Artigo> map0 = null;
      gestor_Artigos0.setArtigos((Map<String, Artigo>) null);
      Boolean boolean0 = new Boolean("A");
      boolean boolean1 = false;
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_cor("A");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      String string0 = "O artigo ";
      String string1 = "-Pfo/\\a`l%Ck#";
      int int0 = (-1969430728);
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("O artigo ", "-Pfo/a`l%Ck#", (-722.958), true, (-274), (-1969430728), (-1730L), (-274), (-491), "O artigo ", (-1969430728), boolean0, (-1730L));
      Dimensao dimensao0 = Dimensao.Grande;
      Encomenda encomenda0 = new Encomenda(set0, (-1730L), dimensao0, (LocalDate) null);
      Set<String> set1 = encomenda0.getEncomenda();
      // Undeclared exception!
      try { 
        gestor_Artigos0.precoFaturouTempo(set1, (LocalDate) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean(true);
      Boolean.getBoolean("z='z");
      Boolean.getBoolean("z='z");
      Boolean.compare(false, false);
      Boolean.logicalAnd(false, false);
      gestor_Artigos0.criar_artigo_mala("Ff6VAUg/", "", 3477.19557870681, true, 1, 1, 117L, 1, 1, "", 758, boolean0, (-4408.67F));
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("Ff6VAUg/");
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      Gestor_Artigos.setTaxaNovo(100.0);
      gestor_Artigos0.pesquisar_artigos_marca_mala("Ff6VAUg/");
      gestor_Artigos0.pesquisar_artigos_cor("");
      Tamanho tamanho0 = Tamanho.S;
      Locale locale0 = Locale.PRC;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Encomenda encomenda0 = new Encomenda();
      Encomenda encomenda1 = encomenda0.clone();
      Encomenda encomenda2 = new Encomenda(encomenda1);
      LocalDate localDate0 = encomenda2.getData();
      gestor_Artigos0.vendaTotal(set0, localDate0);
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_cor("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Ff6VAUg/ Marca:  Pre\u00E7o base: 3477.19557870681 Novo: true Estado de uso: 1 N\u00FAmero de utilizadores: 1 Disponivel: true Id da transportadora: 117 Id do vendedor: 1 } Dimens\u00E3o: 1 Material:  Ano da Cole\u00E7\u00E3o: 758 Premium: true Valoriza\u00E7\u00E3o: -4408.67}\n");
      gestor_Artigos0.toString();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2339));
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2030), 5, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 5, false, 1368);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Long.getLong("", (Long) null);
      Tamanho tamanho0 = Tamanho.XL;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("oEQ$omS=l_-", "", 0.0, false, 1813, 4428, 1813, long0, tamanho0, padrao0);
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(1813);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("y}d1sW");
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2339));
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2030), 5, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 5, false, 1368);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Long.getLong("", (Long) null);
      // Undeclared exception!
      try { 
        gestor_Artigos0.criar_artigo_sapatilhas("", "", 4428, false, (-2339), 1813, (Long) null, 0, 1368, false, "oEQ$omS=l_-", (-2030), false, (-2030));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2339));
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2030), 5, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 5, false, 1368);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Long.getLong("", (Long) null);
      Tamanho tamanho0 = Tamanho.XL;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("oEQ$omS=l_-", "", 0.0, false, 1813, 4428, 1813, long0, tamanho0, padrao0);
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(1368);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("y}d1sW");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      Long long0 = new Long(1813);
      Tamanho tamanho0 = Tamanho.S;
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.criar_artigo_tshirt("p", "p", (-983.1227473512121), false, 1813, 1813, 831L, long0, tamanho0, padrao0);
      Integer integer0 = new Integer(3282);
      Mala mala0 = new Mala();
      Mala mala1 = new Mala(mala0);
      hashMap0.put(integer0, mala1);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("A1");
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(1813);
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2856));
      gestor_Artigos0.artigoToString("A1");
      Boolean boolean0 = new Boolean(false);
      Boolean.getBoolean("A2");
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      gestor_Artigos0.pesquisar_artigos_material("A");
      // Undeclared exception!
      try { 
        gestor_Artigos0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo(0.5);
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_cor("");
      gestor_Artigos0.pesquisar_artigos_material((String) null);
      Boolean boolean0 = Boolean.TRUE;
      gestor_Artigos0.criar_artigo_mala((String) null, "", 0.5, false, 10, 0, 145L, 145L, 0, "", 0, boolean0, 0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("Sapatilha");
      Boolean boolean1 = new Boolean(false);
      gestor_Artigos0.criar_artigo_mala("9", "yu54eZ5s", (-1.0), true, (-1), (-1), (-1020L), (-1), (-1), "LpF^NT`.1iO'", (-1), boolean1, 0.0F);
      gestor_Artigos0.pesquisar_artigos_marca_mala("");
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2922));
      gestor_Artigos0.pesquisar_artigos_marca_mala("A2");
      gestor_Artigos0.pesquisar_artigos_dimensão_mala((-2922));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2339));
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2030), 5, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 5, false, 1368);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Long.getLong("", (Long) null);
      Tamanho tamanho0 = Tamanho.XL;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("oEQ$omS=l_-", "", 0.0, false, 1813, 4428, 1813, long0, tamanho0, padrao0);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("y}d1sW");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = Boolean.valueOf((String) null);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("O artigo ");
      Tamanho tamanho0 = Tamanho.M;
      Padrao padrao0 = Padrao.palmeiras;
      // Undeclared exception!
      try { 
        gestor_Artigos0.criar_artigo_tshirt("", "fwy*l_#,rC`&>ag&", 168.8408806540488, true, 3, (-1), (-2659L), (Long) null, tamanho0, padrao0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2339));
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2030), 5, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 5, false, 1368);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Tamanho tamanho0 = Tamanho.XL;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("oEQ$omS=l_-", "", 0.0, true, 1813, 4428, 1813, long0, tamanho0, padrao0);
      Tamanho tamanho1 = Tamanho.S;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho1);
      gestor_Artigos0.alteraDataToInicio("A3");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Encomenda encomenda0 = new Encomenda();
      Encomenda encomenda1 = new Encomenda(encomenda0);
      Set<String> set0 = encomenda1.removeTudo();
      LocalDate localDate0 = encomenda0.getData();
      encomenda1.toString();
      gestor_Artigos0.precoFaturou(set0, localDate0);
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      gestor_Artigos0.alteraData(encomenda1);
      String string0 = "sU*G{! :oR58W;|[`";
      // Undeclared exception!
      try { 
        gestor_Artigos0.artigoToString("sU*G{! :oR58W;|[`");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Locale locale0 = Locale.JAPANESE;
      HashMap<String, Artigo> hashMap0 = new HashMap<String, Artigo>();
      BiFunction<Object, Object, Mala> biFunction0 = (BiFunction<Object, Object, Mala>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2152));
      hashMap0.replaceAll(biFunction0);
      gestor_Artigos0.setArtigos(hashMap0);
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      gestor_Artigos0.entreDatas(set0, (LocalDate) null, (LocalDate) null);
      gestor_Artigos0.mostrar_gestor((LocalDate) null);
      Long long0 = new Long(0L);
      Tamanho tamanho0 = Tamanho.S;
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.criar_artigo_tshirt("", " n\u00E3o existe!", 0, false, (-2152), (-2152), (-2152), long0, tamanho0, padrao0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo(0.5);
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_material((String) null);
      Boolean boolean0 = Boolean.TRUE;
      gestor_Artigos0.criar_artigo_mala((String) null, "", 0.5, true, 10, 0, 145L, 145L, 0, "", 0, boolean0, 0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("Sapatilha");
      Boolean boolean1 = new Boolean(false);
      gestor_Artigos0.criar_artigo_mala("9", (String) null, (-1.0), true, (-1), (-1), (-1020L), (-1), (-1), "LpF^NT`.1iO'", (-1), boolean1, 0.0F);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_marca_mala(" Data da Cole\u00E7\u00E3o: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      HashMap<String, Object> hashMap1 = new HashMap<String, Object>();
      Gestor_Artigos gestor_Artigos1 = new Gestor_Artigos();
      hashMap1.put("kb(OiK{SP#h^@gP", gestor_Artigos1);
      Set<String> set0 = hashMap1.keySet();
      Period period0 = Period.ofDays((-362));
      long long0 = 1953L;
      Period period1 = period0.minusYears(1953L);
      IsoChronology isoChronology0 = period1.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.entreDatas(set0, localDate0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.getArtigos();
      boolean boolean0 = false;
      Long long0 = new Long(1000);
      gestor_Artigos0.criar_artigo_sapatilhas(",(P9\"u}T1TF$I|&", ",(P9\"u}T1TF$I|&", 2223.480055548818, false, 1000, 1000, long0, 1000, (-5), false, ",(P9\"u}T1TF$I|&", 1000, false, 2223.480055548818);
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      gestor_Artigos0.artigoToString("A1");
      Boolean boolean1 = Boolean.TRUE;
      Gestor_Artigos.getTaxaNovo();
      Boolean.compare(false, true);
      Boolean.compare(false, false);
      gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean1);
      gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas((-403));
      // Undeclared exception!
      try { 
        gestor_Artigos0.id_artigo_para_id_vendedor("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.equals(gestor_Artigos0);
      int int0 = (-26);
      gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas((-26));
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("");
      Gestor_Artigos.getTaxaNovo();
      Encomenda encomenda0 = new Encomenda();
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "");
      // Undeclared exception!
      try { 
        stringBuilder0.insert(10, true);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
         //
         // String index out of range: 10
         //
         verifyException("java.lang.AbstractStringBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo(0.0);
      Long long0 = new Long(0);
      Gestor_Artigos.getTaxaNovo();
      Long long1 = new Long(0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo(0.5);
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_cor("");
      gestor_Artigos0.pesquisar_artigos_material((String) null);
      Boolean boolean0 = Boolean.TRUE;
      gestor_Artigos0.criar_artigo_mala((String) null, "", 0.5, false, 10, 0, 145L, 145L, 0, "", 0, boolean0, 0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("Sapatilha");
      Boolean boolean1 = new Boolean(false);
      gestor_Artigos0.criar_artigo_mala("9", "yu54eZ5s", (-1.0), true, (-1), (-1), (-1020L), (-1), (-1), "LpF^NT`.1iO'", (-1), boolean1, 0.0F);
      gestor_Artigos0.pesquisar_artigos_marca_mala(" Data da Cole\u00E7\u00E3o: ");
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2922));
      gestor_Artigos0.pesquisar_artigos_marca_mala("A2");
      gestor_Artigos0.pesquisar_artigos_dimensão_mala((-2922));
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HashMap<Integer, Artigo> hashMap0 = new HashMap<Integer, Artigo>();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos(hashMap0);
      double double0 = 1.0;
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.precoFaturou(set0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      gestor_Artigos0.toString();
      Gestor_Artigos gestor_Artigos1 = new Gestor_Artigos();
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      gestor_Artigos1.equals((Object) null);
      gestor_Artigos1.pesquisar_artigos_dimensão_mala((-1));
      gestor_Artigos0.equals(gestor_Artigos1);
      // Undeclared exception!
      try { 
        gestor_Artigos0.artigoToString("VX+Ncb;Ufs+d");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Map<String, Artigo> map0 = new HashMap<String, Artigo>();
      Gestor_Artigos gestor_Artigos1 = new Gestor_Artigos();
      int int0 = 384;
      gestor_Artigos1.pesquisar_artigos_ano_colecao(384);
      Encomenda encomenda0 = new Encomenda();
      encomenda0.adicionaArtigo("");
      Encomenda encomenda1 = encomenda0.clone();
      Encomenda encomenda2 = new Encomenda(encomenda1);
      Encomenda.setDiasDevolver(384);
      Boolean boolean0 = Boolean.valueOf(true);
      gestor_Artigos0.criar_artigo_mala("", " +As#.F", (-394.57282527318), false, 958, (-1081), (-1L), (-1880L), 2637, " +As#.F", 0, boolean0, 957.0F);
      // Undeclared exception!
      try { 
        gestor_Artigos0.alteraData(encomenda2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      String string0 = "";
      int int0 = 705;
      Long long0 = new Long((-1559));
      Gestor_Artigos.setTaxaUsado(1231.404211);
      Long.max((-779L), (-201L));
      Long.divideUnsigned((-1L), (-201L));
      Long.max(0L, (-201L));
      gestor_Artigos0.pesquisar_artigos_ano_colecao(1);
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(705);
      gestor_Artigos0.criar_artigo_sapatilhas("", "", 0.0, true, 705, (-1559), long0, (-779L), 1, false, "", (-1559), false, (-779L));
      gestor_Artigos0.id_artigo_para_id_transportadora("A1");
      // Undeclared exception!
      try { 
        gestor_Artigos0.alteraDataToInicio("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Encomenda encomenda0 = new Encomenda();
      gestor_Artigos0.alteraData(encomenda0);
      Map<String, Artigo> map0 = null;
      gestor_Artigos0.setArtigos((Map<String, Artigo>) null);
      Boolean boolean0 = new Boolean("A");
      boolean boolean1 = false;
      Boolean.getBoolean("Encomenda");
      boolean boolean2 = true;
      Tamanho tamanho0 = Tamanho.XL;
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Object object0 = new Object();
      gestor_Artigos0.equals(object0);
      int int0 = 0;
      long long0 = 0L;
      Long long1 = new Long(0);
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.liso;
      gestor_Artigos0.criar_artigo_tshirt("", (String) null, (-1478.88131), false, 0, 0, 0L, long1, tamanho0, padrao0);
      gestor_Artigos0.pesquisar_artigos_cor("nmX$X");
      gestor_Artigos0.pesquisar_artigos_novo_mala((Boolean) null);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_novo_tshirt((Boolean) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = Boolean.valueOf(true);
      Boolean.logicalXor(false, true);
      Boolean.logicalAnd(false, false);
      Boolean.logicalOr(false, true);
      Encomenda encomenda0 = new Encomenda();
      Set<String> set0 = encomenda0.getEncomenda();
      Period period0 = Period.of(0, 0, 1515);
      Period period1 = period0.minusYears((-1L));
      IsoChronology isoChronology0 = period1.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      gestor_Artigos0.precoFaturouTempo(set0, localDate0, localDate0);
      gestor_Artigos0.alteraData(encomenda0);
      gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("$2m");
      // Undeclared exception!
      try { 
        gestor_Artigos0.criar_artigo_mala("D@:L+QQ'y4MZ\\COCf", "", 0.0, false, 0, 5, 0L, 0L, 716, "", 0, (Boolean) null, 0.0F);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.vintageFaturou();
      Boolean boolean0 = Boolean.valueOf("\n");
      Boolean.logicalXor(true, false);
      gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      gestor_Artigos0.pesquisar_artigos_ano_colecao(986);
      gestor_Artigos0.criar_artigo_mala("$K", "\n", 100.0, true, 0, 0, 0L, (-895L), 0, "", (-321), boolean0, (-41.73F));
      Period period0 = Period.ofWeeks(986);
      Period period1 = period0.plusMonths(986);
      IsoChronology isoChronology0 = period1.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      gestor_Artigos0.mostrar_gestor(localDate0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.toString();
      String string0 = ")ud";
      Boolean boolean0 = Boolean.valueOf(")ud");
      Boolean.getBoolean("");
      Boolean.logicalAnd(true, true);
      gestor_Artigos0.criar_artigo_mala("", "", 0.0, true, 0, 0, 0, (-2156L), 0, ")ud", 0, boolean0, (-2156L));
      gestor_Artigos0.pesquisar_artigos_ano_colecao(302);
      Boolean boolean1 = Boolean.FALSE;
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean1);
      // Undeclared exception!
      try { 
        gestor_Artigos0.id_artigo_para_id_transportadora("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      String string0 = "Yg}IhThO*ZHc^4?q*";
      double double0 = 0.0;
      boolean boolean0 = false;
      int int0 = (-271);
      // Undeclared exception!
      try { 
        gestor_Artigos0.id_artigo_para_id_transportadora("Yg}IhThO*ZHc^4?q*");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(907);
      gestor_Artigos0.criar_artigo_sapatilhas("", "v\"9CuVO.Z:", 0.0, true, 0, 907, long0, 0L, 0, false, "@U.Qv`EO$VY-?s!", 838, true, 10.0);
      Long long1 = new Long((-1742L));
      Long.getLong("nl31<EPa,&>CvX");
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.criar_artigo_tshirt("nl31<EPa,&>CvX", "", 0.0, true, (-17), (-630), (-17), long1, tamanho0, padrao0);
      gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(0);
      Boolean boolean0 = new Boolean(false);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      Boolean boolean1 = Boolean.TRUE;
      gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean1);
      Gestor_Artigos.getTaxaNovo();
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      gestor_Artigos0.pesquisar_artigos_marca_mala("-MT`9%-)Va$&hsT");
      // Undeclared exception!
      try { 
        gestor_Artigos0.artigoToString(" Ano da Cole\u00E7\u00E3o: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Tamanho tamanho0 = Tamanho.XL;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      Boolean boolean0 = new Boolean("");
      gestor_Artigos0.criar_artigo_mala((String) null, (String) null, 1.0, false, 512, 512, 512, 537L, 0, (String) null, 0, boolean0, 311.0381F);
      Map<String, Artigo> map0 = gestor_Artigos0.getArtigos();
      gestor_Artigos0.setArtigos(map0);
      gestor_Artigos0.pesquisar_artigos_ano_colecao(0);
      gestor_Artigos0.pesquisar_artigo_id((String) null);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_ano_colecao(0);
      Boolean boolean0 = Boolean.valueOf("");
      Boolean.compare(true, true);
      Boolean.getBoolean("|SuMx0\"d6}1wh<x");
      gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      Boolean.logicalXor(false, false);
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      Boolean.logicalOr(false, false);
      gestor_Artigos0.criar_artigo_mala("|SuMx0\"d6}1wh<x", "Q", (-1023.6148), false, 0, 0, 0, 0, 1, "|SuMx0\"d6}1wh<x", (-1215), boolean0, 4561.641F);
      Map<String, Artigo> map0 = gestor_Artigos0.getArtigos();
      gestor_Artigos0.setArtigos(map0);
      gestor_Artigos0.pesquisar_artigos_material("|SuMx0\"d6}1wh<x");
      Long long0 = new Long(1L);
      gestor_Artigos0.criar_artigo_sapatilhas("", "|SuMx0\"d6}1wh<x", 0.0, false, 0, (-617), long0, 0, 323, false, "cXa|I3otSuu1&99t11", 0, false, (-1023.6148));
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean(true);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      Boolean.getBoolean("");
      gestor_Artigos0.toString();
      Gestor_Artigos.getTaxaNovo();
      Boolean.logicalXor(false, false);
      Boolean boolean1 = Boolean.TRUE;
      gestor_Artigos0.criar_artigo_mala("e|2cj``)*(1XT1@", "RXay^oK2Xm*4fAp(!?~", 0.5, true, 0, 0, (-200L), (-1485L), (-346), "Zq3N", 4, boolean1, (-1200.0F));
      gestor_Artigos0.pesquisar_artigos_material("");
      // Undeclared exception!
      try { 
        gestor_Artigos0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(0);
      Gestor_Artigos.setTaxaUsado(0.0);
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(0);
      Long long0 = new Long(0);
      Tamanho tamanho0 = Tamanho.L;
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.criar_artigo_tshirt("", "", (-3757.8), true, (-638), 0, (-638), long0, tamanho0, padrao0);
      gestor_Artigos0.pesquisar_artigos_material("");
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Encomenda encomenda0 = new Encomenda();
      encomenda0.clone();
      gestor_Artigos0.alteraData(encomenda0);
      Gestor_Artigos.getTaxaNovo();
      Long long0 = new Long(3);
      Long.compare(3, 3);
      Long.max(3, 3093L);
      Long.min(3093L, 864L);
      gestor_Artigos0.criar_artigo_sapatilhas(":7'Mh%yO=O4,", "", 0.5, false, 3, 3, long0, 864L, (-900), false, ":7'Mh%yO=O4,", (-5822), false, 0.5);
      gestor_Artigos0.getArtigos();
      Padrao padrao0 = Padrao.liso;
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      Gestor_Artigos.setTaxaNovo(880.70932678715);
      // Undeclared exception!
      try { 
        gestor_Artigos0.id_artigo_para_id_vendedor(")");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean(false);
      gestor_Artigos0.criar_artigo_mala("4", "Mala", 1.0, false, (-466), (-466), (-466), (-466), (-466), " Id do vendedor: ", 0, boolean0, 0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_novo_mala((Boolean) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Map<String, Artigo> map0 = gestor_Artigos0.getArtigos();
      gestor_Artigos0.setArtigos(map0);
      Map<String, Artigo> map1 = gestor_Artigos0.getArtigos();
      gestor_Artigos0.setArtigos(map1);
      Gestor_Artigos.setTaxaUsado((-3033.14925666));
      Boolean boolean0 = new Boolean(false);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      LocalDate localDate0 = MockLocalDate.now();
      gestor_Artigos0.mostrar_gestor(localDate0);
      gestor_Artigos0.toString();
      Gestor_Artigos.getTaxaUsado();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes(0, 0);
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      LocalDate localDate0 = MockLocalDate.now(clock0);
      gestor_Artigos0.mostrar_gestor(localDate0);
      gestor_Artigos0.setArtigos((Map<String, Artigo>) null);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Gestor_Artigos.setTaxaUsado((-2744.868294997942));
      Gestor_Artigos.getTaxaUsado();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(0);
      gestor_Artigos0.criar_artigo_sapatilhas("w@S5)^{TyV", "w@S5)^{TyV", (-2744.868294997942), false, (-1), 0, long0, (-4307L), 0, true, "9", 784, true, (-2744.868294997942));
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(1922);
      gestor_Artigos0.criar_artigo_sapatilhas("f", "f", 0.01, true, 1922, 1922, long0, 0L, 0, false, "IuX]", 1374, true, 0.5);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_dimensão_mala((-3654));
      Boolean boolean0 = Boolean.FALSE;
      Boolean.logicalXor(false, false);
      gestor_Artigos0.criar_artigo_mala("", "", (-2004.6557145765), true, (-3654), (-3654), (-327L), (-3654), (-3654), "", (-3654), boolean0, 1.0F);
      gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean0);
      gestor_Artigos0.pesquisar_artigos_marca_mala("7l-@H9jayz");
      Boolean boolean1 = Boolean.TRUE;
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean1);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = Boolean.valueOf("yj\"n~i}mrz^,");
      Boolean.compare(false, false);
      gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      try { 
        gestor_Artigos0.colocar_disponivel_artigo("HCWp)#(7V)W");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo HCWp)#(7V)W n\u00E3o existe!
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      String string0 = "Ex%";
      // Undeclared exception!
      try { 
        gestor_Artigos0.alteraDataToInicio("Ex%");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.alteraDataToInicio("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      String string0 = ";*S]";
      boolean boolean0 = true;
      int int0 = 3275;
      int int1 = 1554;
      // Undeclared exception!
      try { 
        gestor_Artigos0.criar_artigo_mala("", "fM", (-1449.01786838), true, 3275, 0, 0L, (-1L), 0, "Gestor_Artigos", 1554, (Boolean) null, (-1L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo(1015.845968);
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Encomenda encomenda0 = new Encomenda();
      Encomenda encomenda1 = new Encomenda(encomenda0);
      Encomenda encomenda2 = encomenda1.clone();
      gestor_Artigos0.alteraData(encomenda2);
      gestor_Artigos0.pesquisar_artigos_marca_mala(" n\u00E3o existe!");
      Tamanho tamanho0 = Tamanho.L;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2339));
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2030), 5, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 5, false, 1368);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Tamanho tamanho0 = Tamanho.XL;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("oEQ$omS=l_-", "", 0.0, false, 1813, 4428, 1813, long0, tamanho0, padrao0);
      Tamanho tamanho1 = Tamanho.S;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho1);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_material("Tamanho");
      gestor_Artigos0.pesquisar_artigos_material((String) null);
      gestor_Artigos0.vintageFaturou();
      Boolean boolean0 = new Boolean(true);
      gestor_Artigos0.criar_artigo_mala("6 n8`B#;SNwV]fsJM", "l", 2693.4132016305, true, (-984), 1, (-406L), (-406L), 1, "l", 1242, boolean0, (-984));
      Gestor_Artigos.getTaxaNovo();
      gestor_Artigos0.equals((Object) null);
      Tamanho tamanho0 = Tamanho.S;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      gestor_Artigos0.vintageFaturou();
      try { 
        gestor_Artigos0.colocar_disponivel_artigo("YgOF ?~sTQBlPwNxQ?");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo YgOF ?~sTQBlPwNxQ? n\u00E3o existe!
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_cor("UvUKs2{p^f");
      gestor_Artigos0.pesquisar_artigos_dimensão_mala((-4409));
      gestor_Artigos0.pesquisar_artigo_id("UvUKs2{p^f");
      gestor_Artigos0.pesquisar_artigos_cor("UvUKs2{p^f");
      Tamanho tamanho0 = Tamanho.S;
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(0);
      gestor_Artigos0.criar_artigo_sapatilhas((String) null, (String) null, 1.0, true, 0, 0, long0, 0L, 0, true, (String) null, 0, true, 0);
      Gestor_Artigos.setTaxaUsado(1.0);
      gestor_Artigos0.equals((Object) null);
      Boolean boolean0 = new Boolean("");
      Boolean.logicalOr(false, true);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      // Undeclared exception!
      try { 
        gestor_Artigos0.pesquisar_artigos_marca_sapatilha("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      // Undeclared exception!
      try { 
        gestor_Artigos0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Gestor_Artigos.getTaxaUsado();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(0);
      gestor_Artigos0.pesquisar_artigos_dimensão_mala((-285));
      // Undeclared exception!
      try { 
        gestor_Artigos0.artigoToString("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Gestor_Artigos.getTaxaNovo();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Gestor_Artigos.setTaxaUsado(0.5);
      String string0 = "\n";
      try { 
        gestor_Artigos0.tirar_disponivel_artigo("\n");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo 
         //  n\u00E3o existe!
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = new Long(0L);
      Tamanho tamanho0 = Tamanho.S;
      Padrao padrao0 = Padrao.liso;
      gestor_Artigos0.criar_artigo_tshirt("TH_%xz", " Ano da Cole\u00E7\u00E3o: ", 1.0, false, 0, 0, 0L, long0, tamanho0, padrao0);
      gestor_Artigos0.pesquisar_artigos_ano_colecao(0);
      gestor_Artigos0.pesquisar_artigos_cor("xs*IPm]");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("");
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Gestor_Artigos.setTaxaUsado((-2329.41351));
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("^B'Gs1jRq1:V", "^B'Gs1jRq1:V", (-2329.41351), true, 1334, 1334, (-1L), 3267L, 1334, "^B'Gs1jRq1:V", 0, boolean0, 0);
      Gestor_Artigos.setTaxaNovo(0.5);
      gestor_Artigos0.toString();
      Gestor_Artigos.getTaxaNovo();
      Gestor_Artigos.getTaxaNovo();
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Gestor_Artigos.getTaxaNovo();
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      String string0 = null;
      // Undeclared exception!
      try { 
        gestor_Artigos0.artigoToString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Long long0 = Long.getLong("", 0L);
      Tamanho tamanho0 = Tamanho.S;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("", "", 0.0, true, (-2845), 1252, (-2845), long0, tamanho0, padrao0);
      Padrao padrao1 = Padrao.riscas;
      gestor_Artigos0.pesquisar_artigos_padrao(padrao1);
      gestor_Artigos0.pesquisar_artigos_cor(" Data da Cole\u00E7\u00E3o: ");
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long((-2351L));
      gestor_Artigos0.criar_artigo_sapatilhas("", "ArtigoExistenteException", 0.0, true, 0, 1013, long0, 0, 0, true, "", 1013, true, 0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean("");
      Boolean.logicalAnd(true, true);
      gestor_Artigos0.pesquisar_artigos_novo_mala(boolean0);
      Gestor_Artigos.setTaxaUsado((-1084.6));
      gestor_Artigos0.vintageFaturou();
      gestor_Artigos0.pesquisar_artigos_cor("");
      Gestor_Artigos.getTaxaUsado();
      gestor_Artigos0.toString();
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = null;
      try {
        gestor_Artigos0 = new Gestor_Artigos((Gestor_Artigos) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      String string0 = "";
      double double0 = (-145.9434827837215);
      boolean boolean0 = true;
      int int0 = (-1077);
      // Undeclared exception!
      try { 
        gestor_Artigos0.id_artigo_para_id_vendedor("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(0);
      Boolean boolean0 = Boolean.valueOf("Gestor_Artigos");
      gestor_Artigos0.pesquisar_artigos_novo_sapatilhas(boolean0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Gestor_Artigos.setTaxaUsado(1285.5574);
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      Boolean boolean0 = new Boolean("!`dIEMk_G");
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_dimensão_mala(2323);
      gestor_Artigos0.pesquisar_artigos_marca_mala("");
      try { 
        gestor_Artigos0.tirar_disponivel_artigo(" CyI6@:i-qoQvK0v[/{");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo  CyI6@:i-qoQvK0v[/{ n\u00E3o existe!
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo(2585.0);
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      Gestor_Artigos.getTaxaUsado();
      Map<String, Artigo> map0 = gestor_Artigos0.getArtigos();
      gestor_Artigos0.setArtigos(map0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt((String) null);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Integer integer0 = new Integer(4839);
      Integer integer1 = new Integer(4839);
      Integer.getInteger("", integer1);
      Integer.getInteger("");
      Integer.getInteger("", integer0);
      gestor_Artigos0.equals(integer0);
      try { 
        gestor_Artigos0.tirar_disponivel_artigo("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo  n\u00E3o existe!
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      String string0 = " Padr\u00E3o: ";
      gestor_Artigos0.pesquisar_artigos_cor("");
      // Undeclared exception!
      try { 
        gestor_Artigos0.id_artigo_para_id_vendedor(" Padr\u00E3o: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Long long0 = new Long(0);
      gestor_Artigos0.criar_artigo_sapatilhas("Gestor_Artigos", " Data da Cole\u00E7\u00E3o: ", 0.25, true, 0, 0, long0, 0L, (-1), true, "e", (-1879048189), false, (-1879048189));
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Encomenda encomenda0 = new Encomenda();
      LocalDate localDate0 = encomenda0.getData();
      gestor_Artigos0.precoFaturou(linkedHashSet0, localDate0);
      gestor_Artigos0.artigoToString("A1");
      gestor_Artigos0.alteraData(encomenda0);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("qoEv=:");
      Boolean boolean0 = new Boolean(true);
      gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      gestor_Artigos0.mostrar_gestor(localDate0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean(true);
      Boolean.getBoolean("z='z");
      Boolean.getBoolean("z='z");
      Boolean.compare(false, false);
      Boolean.logicalAnd(false, false);
      gestor_Artigos0.criar_artigo_mala("Ff6VAUg/", "", 3477.19557870681, true, 1, 1, 117L, 1, 1, "", 758, boolean0, (-4408.67F));
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("Ff6VAUg/");
      Padrao padrao0 = Padrao.riscas;
      gestor_Artigos0.pesquisar_artigos_padrao(padrao0);
      Gestor_Artigos.setTaxaNovo(100.0);
      gestor_Artigos0.pesquisar_artigos_marca_mala("Ff6VAUg/");
      gestor_Artigos0.pesquisar_artigos_cor("");
      Tamanho tamanho0 = Tamanho.S;
      Locale locale0 = Locale.PRC;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Encomenda encomenda0 = new Encomenda();
      encomenda0.clone();
      LocalDate localDate0 = encomenda0.getData();
      gestor_Artigos0.vendaTotal(set0, localDate0);
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_cor("Mala:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Ff6VAUg/ Marca:  Pre\u00E7o base: 3477.19557870681 Novo: true Estado de uso: 1 N\u00FAmero de utilizadores: 1 Disponivel: true Id da transportadora: 117 Id do vendedor: 1 } Dimens\u00E3o: 1 Material:  Ano da Cole\u00E7\u00E3o: 758 Premium: true Valoriza\u00E7\u00E3o: -4408.67}\n");
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_dimensão_mala((-2065));
      gestor_Artigos0.criar_artigo_mala("(#[", "", 0.0, true, 0, 0, 758, 1, 758, "(#[", 222, boolean0, 1);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      Boolean boolean0 = new Boolean((String) null);
      Boolean.getBoolean((String) null);
      Boolean.logicalOr(true, true);
      Boolean.getBoolean("Tamanho");
      Boolean.compare(false, false);
      gestor_Artigos0.criar_artigo_mala("Tamanho", "Tamanho", 0.5, true, 1, 2002, 1, 0L, 3496, "", 2002, boolean0, 2002);
      Boolean.getBoolean("Tamanho");
      Boolean.logicalOr(true, false);
      gestor_Artigos0.criar_artigo_mala("jrxKO^4 I\"E07tPC", "Tamanho", 3496, false, 1, 0, 0L, 3496, 1, "Tamanho", 3496, boolean0, (-1202.37F));
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha(" Cor: ");
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.vintageFaturou();
      Boolean boolean1 = Boolean.valueOf("\n");
      gestor_Artigos0.pesquisar_artigos_novo_mala(boolean1);
      gestor_Artigos0.pesquipesquisar_artigos_tamanho_sapatilhas(2002);
      // Undeclared exception!
      try { 
        gestor_Artigos0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      Gestor_Artigos.setTaxaNovo(0.5);
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_cor("");
      gestor_Artigos0.pesquisar_artigos_material((String) null);
      Boolean boolean0 = Boolean.TRUE;
      gestor_Artigos0.criar_artigo_mala((String) null, "", 0.5, false, 10, 0, 145L, 145L, 0, "", 0, boolean0, 0);
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("Sapatilha");
      Boolean boolean1 = new Boolean(false);
      Boolean.logicalOr(false, true);
      gestor_Artigos0.criar_artigo_mala("9", "yu54eZ5s", (-1.0), true, (-1), (-1), (-1020L), (-1), (-1), "LpF^NT`.1iO'", (-1), boolean1, 0.0F);
      gestor_Artigos0.pesquisar_artigos_marca_mala(" Data da Cole\u00E7\u00E3o: ");
      gestor_Artigos0.pesquisar_artigos_ano_colecao((-2922));
      gestor_Artigos0.pesquisar_artigos_marca_mala("A2");
      gestor_Artigos0.pesquisar_artigos_dimensão_mala((-2922));
      gestor_Artigos0.getArtigos();
      gestor_Artigos0.pesquisar_artigos_material(" Estado: ");
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.pesquisar_artigos_material((String) null);
      Boolean boolean0 = Boolean.TRUE;
      gestor_Artigos0.pesquisar_artigos_marca_tshirt("Sapatilha");
      Boolean boolean1 = new Boolean(false);
      Boolean.compare(false, true);
      gestor_Artigos0.criar_artigo_mala("9", "yu54eZ5s", (-1.0), true, (-1), (-1), (-1020L), (-1), (-1), "LpF^NT`.1iO'", (-1), boolean1, 0.0F);
      gestor_Artigos0.pesquisar_artigos_marca_mala("LpF^NT`.1iO'");
      try { 
        gestor_Artigos0.colocar_disponivel_artigo("R =GFLM");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo R =GFLM n\u00E3o existe!
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.toString();
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("&hmY^T\"fwQ*~ChV");
      Boolean boolean0 = Boolean.FALSE;
      gestor_Artigos0.criar_artigo_mala("", "", (-1248.303), false, 0, 0, 1328L, 1328L, 0, "bIW?W@u^~.sL1", 4428, boolean0, 1328L);
      String string0 = gestor_Artigos0.pesquisar_artigos_ano_colecao((-2339));
      Long long0 = new Long((-2339));
      gestor_Artigos0.criar_artigo_sapatilhas("", "bIW?W@u^~.sL1", (-1395.6660303), false, (-2030), 0, long0, (-1L), 1368, false, "t#>vDz<!'i]kh", 0, false, 1368);
      String string1 = gestor_Artigos0.pesquisar_artigos_marca_sapatilha("A1");
      Long.getLong("", (Long) null);
      Tamanho tamanho0 = Tamanho.XL;
      Padrao padrao0 = Padrao.palmeiras;
      gestor_Artigos0.criar_artigo_tshirt("oEQ$omS=l_-", "", 0.0, false, 1813, 4428, 1813, long0, tamanho0, padrao0);
      gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      String string2 = gestor_Artigos0.pesquisar_artigos_marca_tshirt("y}d1sW");
      assertTrue(string2.equals((Object)string0));
      
      String string3 = gestor_Artigos0.pesquisar_artigos_material((String) null);
      assertTrue(string3.equals((Object)string1));
      
      String string4 = gestor_Artigos0.pesquipesquisar_artigos_tamanho__tshit(tamanho0);
      assertEquals("T-shirt:: {Artigo:: { C\u00F3digo de barras: A3 Descri\u00E7\u00E3o: oEQ$omS=l_- Marca:  Pre\u00E7o base: 0.0 Novo: false Estado de uso: 1813 N\u00FAmero de utilizadores: 4428 Disponivel: true Id da transportadora: 1813 Id do vendedor: -2339 } Tamanho: XL Padr\u00E3o: palmeiras}\n", string4);
      
      String string5 = gestor_Artigos0.pesquisar_artigos_novo_tshirt(boolean0);
      assertEquals("T-shirt:: {Artigo:: { C\u00F3digo de barras: A3 Descri\u00E7\u00E3o: oEQ$omS=l_- Marca:  Pre\u00E7o base: 0.0 Novo: false Estado de uso: 1813 N\u00FAmero de utilizadores: 4428 Disponivel: true Id da transportadora: 1813 Id do vendedor: -2339 } Tamanho: XL Padr\u00E3o: palmeiras}\n", string5);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos((Map<Integer, Artigo>) null);
      int int0 = 0;
      gestor_Artigos0.pesquisar_artigos_ano_colecao(0);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("");
      gestor_Artigos0.pesquisar_artigo_id("O artigo ");
      gestor_Artigos0.toString();
      try { 
        gestor_Artigos0.tirar_disponivel_artigo("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo  n\u00E3o existe!
         //
         verifyException("Gestor_Artigos", e);
      }
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      Gestor_Artigos gestor_Artigos0 = new Gestor_Artigos();
      gestor_Artigos0.toString();
      Gestor_Artigos.setTaxaNovo(6.257543);
      Gestor_Artigos.setTaxaNovo(6.257543);
      gestor_Artigos0.pesquisar_artigos_marca_sapatilha("");
      gestor_Artigos0.vintageFaturou();
      gestor_Artigos0.equals("");
      gestor_Artigos0.toString();
      try { 
        gestor_Artigos0.tirar_disponivel_artigo("`O\"^(");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O artigo `O\"^( n\u00E3o existe!
         //
         verifyException("Gestor_Artigos", e);
      }
  }
}
