/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 09:55:12 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Sapatilha_ESTest extends Sapatilha_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setAtacadores(true);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setPremium(false);
      sapatilha0.setEstado_uso(2805);
      sapatilha0.toString();
      sapatilha0.toString();
      sapatilha0.toString();
      sapatilha0.toString();
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha1.setPremium(true);
      sapatilha1.preco_atual(localDate0);
      sapatilha1.preco_atual(localDate0);
      sapatilha1.preco_atual(localDate0);
      Sapatilha sapatilha2 = sapatilha1.clone();
      sapatilha2.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: false Estado de uso: 2805 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Tamanho: 0 Atacadores: true Cor:  Data da Cole\u00E7\u00E3o: 0 Premium: false Desconto: 0.0}");
      Sapatilha sapatilha3 = sapatilha2.clone();
      sapatilha0.equals(sapatilha3);
      sapatilha0.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: false Estado de uso: 2805 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Tamanho: 0 Atacadores: true Cor:  Data da Cole\u00E7\u00E3o: 0 Premium: false Desconto: 0.0}");
      sapatilha2.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: false Estado de uso: 2805 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Tamanho: 0 Atacadores: true Cor:  Data da Cole\u00E7\u00E3o: 0 Premium: false Desconto: 0.0}");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Long long0 = new Long((-3L));
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setData_venda((LocalDate) null);
      // Undeclared exception!
      try { 
        sapatilha0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha0.setAnoColecao(2915);
      sapatilha1.equals(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.setAtacadores(true);
      sapatilha1.getDesconto();
      sapatilha1.setDisponivel(false);
      sapatilha1.setDesconto((-1.0));
      LocalDate localDate0 = sapatilha1.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setTamanho(0);
      sapatilha0.setPremium(false);
      sapatilha1.equals(sapatilha0);
      sapatilha0.setTamanho(0);
      sapatilha0.getTamanho();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.getDesconto();
      sapatilha1.setDisponivel(false);
      sapatilha1.setDesconto((-1.0));
      LocalDate localDate0 = sapatilha1.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setTamanho(0);
      sapatilha0.setPremium(false);
      sapatilha1.equals(sapatilha0);
      sapatilha0.setTamanho(0);
      sapatilha0.getTamanho();
      sapatilha0.clone();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.setAtacadores(true);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha1.mostrar(localDate0);
      sapatilha1.getDesconto();
      sapatilha1.setDisponivel(false);
      sapatilha1.setDesconto((-1.0));
      LocalDate localDate1 = sapatilha1.getData_venda();
      sapatilha0.preco_atual(localDate1);
      sapatilha0.setTamanho(2433);
      sapatilha0.setPremium(false);
      sapatilha1.equals(sapatilha0);
      sapatilha0.setTamanho(0);
      sapatilha0.getTamanho();
      sapatilha1.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: false Estado de uso: -1 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Tamanho: 0 Atacadores: true Cor:  Data da Cole\u00E7\u00E3o: 0 Premium: false Desconto: 0.0} Pre\u00E7o atual: 0.01\u20AC \n");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.toString();
      sapatilha1.equals(sapatilha0);
      sapatilha1.setAtacadores(true);
      sapatilha1.getDesconto();
      sapatilha1.setDisponivel(false);
      sapatilha1.setDesconto((-1.0));
      LocalDate localDate0 = sapatilha1.getData_venda();
      sapatilha1.setTamanho(1372);
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setTamanho(0);
      sapatilha0.setPremium(false);
      sapatilha1.equals(sapatilha0);
      sapatilha0.setTamanho(0);
      sapatilha0.getTamanho();
      sapatilha0.clone();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Double double0 = new Double((-1361.957638190473));
      Long long0 = new Long(0L);
      Sapatilha sapatilha0 = new Sapatilha((String) null, ";M$5$`(,,$J\"pV{%X]", double0, true, 10, 10, long0, long0, 1472, true, ";M$5$`(,,$J\"pV{%X]", 2146403080, true, 1829.231384);
      sapatilha0.setAtacadores(true);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha0.equals(localDate0);
      sapatilha1.toString();
      sapatilha0.toString();
      sapatilha0.equals(double0);
      sapatilha1.toString();
      sapatilha1.preco_atual(localDate0);
      Sapatilha sapatilha2 = sapatilha1.clone();
      sapatilha0.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: null Marca: ;M$5$`(,,$J\"pV{%X] Pre\u00E7o base: -1361.957638190473 Novo: true Estado de uso: 10 N\u00FAmero de utilizadores: 10 Disponivel: true Id da transportadora: 0 Id do vendedor: 0 } Tamanho: 1472 Atacadores: true Cor: ;M$5$`(,,$J\"pV{%X] Data da Cole\u00E7\u00E3o: 2146403080 Premium: true Desconto: 1829.231384}");
      sapatilha0.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: null Marca: ;M$5$`(,,$J\"pV{%X] Pre\u00E7o base: -1361.957638190473 Novo: true Estado de uso: 10 N\u00FAmero de utilizadores: 10 Disponivel: true Id da transportadora: 0 Id do vendedor: 0 } Tamanho: 1472 Atacadores: true Cor: ;M$5$`(,,$J\"pV{%X] Data da Cole\u00E7\u00E3o: 2146403080 Premium: true Desconto: 1829.231384}");
      // Undeclared exception!
      try { 
        sapatilha1.equals(sapatilha2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Artigo.criaCodigo();
      sapatilha0.equals(sapatilha0);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.toString();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.setData_venda(localDate0);
      sapatilha0.setTamanho(0);
      sapatilha0.toString();
      sapatilha0.setDesconto((-4600.5253));
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.setCor("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: false Estado de uso: -1 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Tamanho: 0 Atacadores: false Cor:  Data da Cole\u00E7\u00E3o: 0 Premium: false Desconto: 0.0}");
      sapatilha1.setAnoColecao((-1));
      sapatilha0.setAtacadores(false);
      sapatilha0.equals(sapatilha1);
      sapatilha0.getTamanho();
      sapatilha1.getDesconto();
      sapatilha1.getCor();
      sapatilha0.setTamanho(1675);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setTransportadora(1L);
      sapatilha0.setDisponivel(false);
      sapatilha0.setNovo(true);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.isAtacadores();
      sapatilha0.isAtacadores();
      sapatilha0.isAtacadores();
      sapatilha0.getAnoColecao();
      sapatilha0.setPreco_base(0.01);
      sapatilha0.getAnoColecao();
      sapatilha0.setTamanho(45);
      sapatilha0.getDesconto();
      sapatilha0.equals("c^nkG]");
      sapatilha0.getDesconto();
      sapatilha0.isAtacadores();
      sapatilha0.isAtacadores();
      sapatilha0.isAtacadores();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.isPremium();
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha1.setCodigo_barras("");
      sapatilha0.clone();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Double double0 = new Double((-1010.04479));
      Long long0 = new Long((-1057L));
      Long long1 = new Long((-1057L));
      Sapatilha sapatilha0 = new Sapatilha("", "", double0, false, (-353), (-353), long0, long1, (-1), true, "Z=Z", (-2132), true, 0.0);
      sapatilha0.toString();
      sapatilha0.setAnoColecao((-1));
      sapatilha0.isPremium();
      Sapatilha sapatilha1 = sapatilha0.clone();
      boolean boolean0 = true;
      // Undeclared exception!
      try { 
        sapatilha1.preco_atual((LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Sapatilha", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Double double0 = new Double(1967.3758949);
      Long long0 = new Long(0);
      Sapatilha sapatilha0 = new Sapatilha("[PlG/jT{ W?2~|", "7mOjU`]Y\"?y^$nSw&", double0, true, 0, 0, long0, long0, 1210, true, "", 1210, false, (-76.67192504796837));
      Sapatilha sapatilha1 = sapatilha0.clone();
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setAtacadores(false);
      LocalDate localDate1 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate1);
      sapatilha1.isPremium();
      sapatilha1.clone();
      sapatilha0.setDesconto((-1.0));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Double double0 = new Double(1991.3545032824609);
      Long long0 = new Long((-1));
      Long long1 = new Long((-1));
      Sapatilha sapatilha0 = new Sapatilha("zcU>XDkS5%<I$x[", "zcU>XDkS5%<I$x[", double0, true, (-1), (-2305), long0, long1, (-1), false, " Premium: ", (-1), true, 0.0);
      Artigo.contador = 0L;
      sapatilha0.setAtacadores(true);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.isPremium();
      sapatilha0.isPremium();
      sapatilha0.isAtacadores();
      sapatilha0.setTamanho((-1));
      sapatilha0.isPremium();
      sapatilha0.getCor();
      sapatilha0.setAtacadores(true);
      sapatilha0.toString();
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha1.setTamanho((-2305));
      sapatilha0.getAnoColecao();
      sapatilha1.clone();
      sapatilha0.getDesconto();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Double double0 = new Double((-226.62980250551036));
      Long long0 = new Long((-984L));
      Long long1 = new Long((-10L));
      Sapatilha sapatilha0 = new Sapatilha("B\"N':t3", "K{d=", double0, true, 284, 778, long0, long1, 284, true, "B\"N':t3", 284, true, 778);
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.getTamanho();
      sapatilha0.getAnoColecao();
      sapatilha0.setPremium(true);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.toString();
      sapatilha0.setPreco_base(610.4903);
      sapatilha0.setCor(" Novo: ");
      sapatilha0.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: false Estado de uso: -1 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Tamanho: 0 Atacadores: false Cor:  Data da Cole\u00E7\u00E3o: 0 Premium: false Desconto: 0.0}");
      sapatilha0.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: Artigo invalido Marca: Artigo invalido Pre\u00E7o base: 0.0 Novo: false Estado de uso: -1 N\u00FAmero de utilizadores: -1 Disponivel: false Id da transportadora: -1 Id do vendedor: -1 } Tamanho: 0 Atacadores: false Cor:  Data da Cole\u00E7\u00E3o: 0 Premium: false Desconto: 0.0}");
      sapatilha0.toString();
      sapatilha0.setAnoColecao(0);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      Sapatilha sapatilha1 = sapatilha0.clone();
      Artigo.setContador(2L);
      Sapatilha sapatilha2 = sapatilha1.clone();
      sapatilha0.preco_atual(localDate0);
      sapatilha2.preco_atual(localDate0);
      sapatilha2.clone();
      sapatilha1.toString();
      sapatilha0.toString();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setDisponivel(false);
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha1.setAnoColecao(0);
      sapatilha1.setData_venda((LocalDate) null);
      Artigo.contador = (-664L);
      sapatilha0.setMarca("~");
      sapatilha0.setAtacadores(false);
      sapatilha0.setTamanho(45);
      Sapatilha sapatilha2 = sapatilha0.clone();
      sapatilha2.setPreco_base(2598.34001987105);
      sapatilha2.getDesconto();
      sapatilha2.toString();
      sapatilha2.setPremium(true);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Double double0 = new Double(0.0);
      Long long0 = new Long(1554);
      Long long1 = new Long((-1L));
      Sapatilha sapatilha0 = new Sapatilha("}", "}", double0, true, 337, 1554, long0, long1, 337, false, "}", 337, false, 1554);
      sapatilha0.setDesconto(0.0);
      sapatilha0.setCor("}");
      sapatilha0.isAtacadores();
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha0.getCor();
      sapatilha1.equals(double0);
      LocalDate localDate0 = sapatilha1.getData_venda();
      sapatilha1.preco_atual(localDate0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Double double0 = new Double((-556.0472479097615));
      Long long0 = new Long(638);
      Sapatilha sapatilha0 = new Sapatilha("", "", double0, true, 638, 638, long0, long0, (-461), true, "", 648, true, (-556.0472479097615));
      sapatilha0.toString();
      sapatilha0.setEstado_uso(3527);
      sapatilha0.setCor("");
      sapatilha0.getTamanho();
      sapatilha0.getAnoColecao();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      LocalDate localDate0 = sapatilha1.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.getDesconto();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Sapatilha sapatilha0 = null;
      try {
        sapatilha0 = new Sapatilha((Sapatilha) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Double double0 = new Double(0.0);
      Long long0 = new Long(3229);
      Sapatilha sapatilha0 = new Sapatilha("0.00", " Data da Cole\u00E7\u00E3o: ", double0, false, 3229, 3229, long0, long0, 3229, true, "0.00", (-4829), true, 2424.494031488528);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.setAtacadores(true);
      sapatilha1.getDesconto();
      sapatilha1.setDisponivel(false);
      sapatilha1.setDesconto((-1.0));
      LocalDate localDate0 = sapatilha1.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setTamanho(0);
      sapatilha0.setPremium(false);
      sapatilha1.equals(sapatilha0);
      sapatilha0.setTamanho(0);
      sapatilha0.getTamanho();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCor("m11m?5<H.c ");
      sapatilha0.setMarca("");
      sapatilha0.isAtacadores();
      sapatilha0.getTamanho();
      Sapatilha sapatilha1 = sapatilha0.clone();
      Artigo.contador = 2L;
      sapatilha1.getCor();
      sapatilha1.setAtacadores(true);
      sapatilha0.toString();
      sapatilha0.getTamanho();
      sapatilha0.getCor();
      sapatilha1.getTamanho();
      sapatilha0.getTamanho();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setDescricao("");
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      Artigo.criaCodigo();
      sapatilha0.setAtacadores(false);
      sapatilha0.setTamanho((-1718));
      sapatilha0.setCor(")_+GcmY*L(K!VL");
      sapatilha0.getTamanho();
      sapatilha0.getCor();
      sapatilha0.getAnoColecao();
      sapatilha0.setCor("");
      sapatilha0.setDesconto(0.0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Double double0 = new Double(282.7838);
      Long long0 = new Long(1L);
      Sapatilha sapatilha0 = new Sapatilha("", "", double0, false, (-1335), (-1335), long0, long0, (-1335), true, "", (-1335), true, 0.0);
      sapatilha0.setCor("");
      sapatilha0.setEstado_uso(8);
      sapatilha0.setAtacadores(true);
      sapatilha0.isPremium();
      sapatilha0.setDesconto(0.0);
      sapatilha0.setPremium(true);
      sapatilha0.getAnoColecao();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCor(" Marca: ");
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.getAnoColecao();
      sapatilha0.getData_venda();
      sapatilha0.equals(sapatilha1);
      sapatilha1.setPremium(true);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCor("");
      sapatilha0.setAtacadores(true);
      sapatilha0.isAtacadores();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCor(" Atacadores: ");
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setNovo(true);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setPremium(true);
      sapatilha0.isPremium();
      sapatilha0.setAnoColecao(355);
      sapatilha0.toString();
      sapatilha0.isPremium();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Double double0 = new Double(0.0);
      Long long0 = new Long((-1));
      Long long1 = new Long(0L);
      Sapatilha sapatilha0 = new Sapatilha(" Tamanho: ", "Artigo:: {", double0, true, 1923, (-1), long0, long1, (-1597), true, " Tamanho: ", 1923, true, 1923);
      sapatilha0.getAnoColecao();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Double double0 = new Double((-1480.46523848));
      Long long0 = new Long(1L);
      Sapatilha sapatilha0 = new Sapatilha("A", "A", double0, true, 0, 0, long0, long0, (-223), true, "A", (-223), true, 0.0);
      sapatilha0.clone();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Double double0 = new Double((-103.568135987554));
      Long long0 = new Long(0L);
      Sapatilha sapatilha0 = new Sapatilha(" Disponivel: ", "TjAZ", double0, false, (-695), 1141, long0, long0, 0, false, (String) null, 849, false, (-695));
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha0.setDesconto((-695));
      sapatilha0.getDesconto();
      sapatilha0.getCor();
      sapatilha1.setPremium(true);
      sapatilha0.isAtacadores();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Double double0 = new Double(707.0);
      Long long0 = new Long(0);
      Sapatilha sapatilha0 = new Sapatilha((String) null, (String) null, double0, false, 0, 0, long0, long0, 0, false, "R", 0, false, (-622.0));
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.getDesconto();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCodigo_barras("\u20AC ");
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      Sapatilha sapatilha2 = new Sapatilha(sapatilha1);
      sapatilha2.isAtacadores();
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setPreco_base((-3145.023337));
      sapatilha0.setEstado_uso(1700);
      sapatilha0.setAnoColecao(1700);
      sapatilha0.setAnoColecao((-2959));
      sapatilha0.clone();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Double double0 = new Double(10.0);
      Long long0 = new Long(0L);
      Sapatilha sapatilha0 = new Sapatilha("", "", double0, false, (-1340), (-1015), long0, long0, (-1015), false, "", (-1340), true, (-1340));
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha1.clone();
      sapatilha0.clone();
      sapatilha0.isPremium();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.isPremium();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.clone();
      sapatilha1.preco_atual((LocalDate) null);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setPremium(true);
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      Sapatilha sapatilha2 = sapatilha1.clone();
      sapatilha2.toString();
      sapatilha0.getTamanho();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setN_utilizadores(326);
      sapatilha0.setDesconto(393.0);
      sapatilha0.setAnoColecao(326);
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha1.setAtacadores(false);
      sapatilha0.getDesconto();
      sapatilha0.isAtacadores();
      sapatilha1.setDisponivel(false);
      sapatilha0.setAnoColecao((-2424));
      sapatilha0.getDesconto();
      sapatilha1.setAtacadores(false);
      sapatilha0.equals((Object) null);
      sapatilha0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setCodigo_barras("v` GfmW83z");
      sapatilha0.clone();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Double double0 = new Double((-1.0));
      Long long0 = new Long(0L);
      Sapatilha sapatilha0 = null;
      try {
        sapatilha0 = new Sapatilha("", "!H6{$*N9za", double0, false, 0, 1551, (Long) null, long0, 3123, false, "x{", (-1716), false, (-950.4398853280768));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.getCor();
      sapatilha0.setTamanho(10);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Double double0 = new Double((-271.59900679));
      Long long0 = new Long((-178));
      Long long1 = new Long((-94L));
      Sapatilha sapatilha0 = new Sapatilha("v*Ok^", "v*Ok^", double0, false, (-178), (-178), long0, long1, 1, false, "v*Ok^", 1, false, (-94L));
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setAnoColecao(0);
      sapatilha0.getDesconto();
      sapatilha0.getCor();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha1.preco_atual(localDate0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.getAnoColecao();
      sapatilha0.equals("");
      sapatilha0.setDesconto(2017.3791218);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha();
      sapatilha0.equals(sapatilha1);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      Artigo.setCodigo("G9jGp0v|eUW*hjj");
      sapatilha1.toString();
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setDesconto(0.0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      String string0 = Artigo.codigo;
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha0.setCor("A");
      sapatilha1.preco_atual((LocalDate) null);
      Artigo.setContador(2L);
      sapatilha1.equals(sapatilha0);
      sapatilha0.toString();
      Artigo.criaCodigo();
      sapatilha1.preco_atual((LocalDate) null);
      sapatilha1.setAtacadores(false);
      sapatilha1.equals(sapatilha0);
      sapatilha1.preco_atual((LocalDate) null);
      sapatilha0.toString();
      Sapatilha sapatilha2 = sapatilha0.clone();
      sapatilha2.setDesconto(0.01);
      Sapatilha sapatilha3 = sapatilha1.clone();
      sapatilha3.clone();
      Sapatilha sapatilha4 = sapatilha2.clone();
      sapatilha4.setPremium(false);
      sapatilha3.setDescricao("I0r?");
      Artigo.setContador((-1L));
      Sapatilha sapatilha5 = sapatilha4.clone();
      LocalDate localDate0 = sapatilha3.getData_venda();
      sapatilha5.preco_atual(localDate0);
      sapatilha1.toString();
      sapatilha2.toString();
      sapatilha2.preco_atual(localDate0);
      sapatilha4.preco_atual((LocalDate) null);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      Artigo.contador = 2L;
      sapatilha0.setAnoColecao((-2145339));
      sapatilha1.equals(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.setAtacadores(true);
      sapatilha1.getDesconto();
      sapatilha1.setDisponivel(false);
      sapatilha1.setDesconto((-1.0));
      sapatilha1.getData_venda();
      sapatilha0.setTamanho(0);
      sapatilha0.setPremium(false);
      sapatilha1.equals(sapatilha0);
      sapatilha0.setTamanho(0);
      sapatilha0.getTamanho();
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Double double0 = new Double((-1588.27));
      Long long0 = new Long((-2147481500));
      Sapatilha sapatilha0 = new Sapatilha("T!O>2larwt8zLW?%T", "T!O>2larwt8zLW?%T", double0, true, (-2147481500), 3871, long0, long0, 3871, false, "T!O>2larwt8zLW?%T", (-2146), false, 100.0);
      sapatilha0.setCor("T!O>2larwt8zLW?%T");
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.equals(localDate0);
      sapatilha0.toString();
      sapatilha0.toString();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setNovo(true);
      sapatilha0.equals("gGOj.TEABL*3eFTBS");
      sapatilha0.equals("T!O>2larwt8zLW?%T");
      sapatilha0.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: T!O>2larwt8zLW?%T Marca: T!O>2larwt8zLW?%T Pre\u00E7o base: -1588.27 Novo: true Estado de uso: -2147481500 N\u00FAmero de utilizadores: 3871 Disponivel: true Id da transportadora: -2147481500 Id do vendedor: -2147481500 } Tamanho: 3871 Atacadores: false Cor: T!O>2larwt8zLW?%T Data da Cole\u00E7\u00E3o: -2146 Premium: false Desconto: 100.0}");
      sapatilha0.clone();
      Sapatilha sapatilha1 = sapatilha0.clone();
      Sapatilha sapatilha2 = new Sapatilha(sapatilha0);
      sapatilha2.setDesconto((-1.0));
      sapatilha1.equals(sapatilha2);
      sapatilha2.equals(sapatilha0);
      sapatilha1.equals(sapatilha2);
      LocalDate localDate1 = sapatilha2.getData_venda();
      sapatilha2.preco_atual(localDate1);
      sapatilha0.equals(localDate1);
      sapatilha2.toString();
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Double double0 = new Double((-1.0));
      Long long0 = new Long(0L);
      Long long1 = new Long(1705L);
      Sapatilha sapatilha0 = new Sapatilha("x7T{|g-+R]PV}~G)ud", "Yn+", double0, false, (-1757), 1, long0, long1, 45, false, "n[{kY&r", 45, false, 1705L);
      sapatilha0.equals(long0);
      sapatilha0.equals(sapatilha0);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Double double0 = new Double((-1.0));
      Long long0 = new Long(1);
      Long long1 = new Long(1705L);
      Sapatilha sapatilha0 = new Sapatilha("x7T{|g-+R]PV}~G)ud", "x7T{|g-+R]PV}~G)ud", double0, false, (-1757), 1, long0, long1, 45, false, "x7T{|g-+R]PV}~G)ud", 45, false, 1705L);
      sapatilha0.equals(long0);
      Sapatilha sapatilha1 = new Sapatilha();
      sapatilha0.equals(sapatilha1);
      sapatilha0.toString();
      sapatilha0.equals("x7T{|g-+R]PV}~G)ud");
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Double double0 = new Double((-1354.234316340906));
      int int0 = 10;
      Long long0 = new Long(0L);
      int int1 = 2146403080;
      Sapatilha sapatilha0 = new Sapatilha((String) null, ";M$5$`(,,$J\"pV{%X]", double0, true, 10, 10, long0, long0, 1472, true, ";M$5$`(,,$J\"pV{%X]", 2146403080, true, 1829.231384);
      sapatilha0.setAtacadores(true);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha0.equals((Object) null);
      sapatilha1.toString();
      sapatilha0.toString();
      sapatilha0.equals(double0);
      sapatilha1.toString();
      sapatilha1.preco_atual(localDate0);
      sapatilha0.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: null Marca: ;M$5$`(,,$J\"pV{%X] Pre\u00E7o base: -1354.234316340906 Novo: true Estado de uso: 10 N\u00FAmero de utilizadores: 10 Disponivel: true Id da transportadora: 0 Id do vendedor: 0 } Tamanho: 1472 Atacadores: true Cor: ;M$5$`(,,$J\"pV{%X] Data da Cole\u00E7\u00E3o: 2146403080 Premium: true Desconto: 1829.231384}");
      sapatilha0.equals("Sapatilhas:: {Artigo:: { C\u00F3digo de barras: A1 Descri\u00E7\u00E3o: null Marca: ;M$5$`(,,$J\"pV{%X] Pre\u00E7o base: -1354.234316340906 Novo: true Estado de uso: 10 N\u00FAmero de utilizadores: 10 Disponivel: true Id da transportadora: 0 Id do vendedor: 0 } Tamanho: 1472 Atacadores: true Cor: ;M$5$`(,,$J\"pV{%X] Data da Cole\u00E7\u00E3o: 2146403080 Premium: true Desconto: 1829.231384}");
      // Undeclared exception!
      try { 
        sapatilha1.equals(sapatilha0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Artigo", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.equals(sapatilha0);
      sapatilha1.setAtacadores(true);
      sapatilha1.getDesconto();
      sapatilha1.setDesconto(0.0);
      LocalDate localDate0 = sapatilha1.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.setTamanho(0);
      sapatilha0.setPremium(false);
      sapatilha1.equals(sapatilha0);
      sapatilha0.setTamanho(0);
      sapatilha0.getTamanho();
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      Sapatilha sapatilha1 = new Sapatilha(sapatilha0);
      sapatilha1.setAtacadores(true);
      sapatilha1.getDesconto();
      sapatilha1.setDisponivel(false);
      sapatilha1.setDesconto(2L);
      sapatilha0.setTamanho((-28));
      sapatilha0.setPremium(false);
      sapatilha1.equals(sapatilha0);
      sapatilha0.setTamanho(0);
      sapatilha0.getTamanho();
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Sapatilha sapatilha0 = new Sapatilha();
      sapatilha0.setTransportadora(1L);
      sapatilha0.setDisponivel(false);
      sapatilha0.setNovo(true);
      LocalDate localDate0 = sapatilha0.getData_venda();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.isAtacadores();
      sapatilha0.isAtacadores();
      sapatilha0.getAnoColecao();
      sapatilha0.setPreco_base(0.01);
      sapatilha0.getAnoColecao();
      sapatilha0.setTamanho(51);
      sapatilha0.getDesconto();
      sapatilha0.equals("c^nkG]");
      sapatilha0.getDesconto();
      sapatilha0.isAtacadores();
      sapatilha0.isAtacadores();
      sapatilha0.isAtacadores();
      sapatilha0.preco_atual(localDate0);
      sapatilha0.isPremium();
      Sapatilha sapatilha1 = sapatilha0.clone();
      sapatilha1.setCodigo_barras(" N\u00FAmero de utilizadores: ");
      sapatilha0.clone();
      assertEquals(51, sapatilha0.getTamanho());
  }
}
