/*
 * This file was automatically generated by EvoSuite
 * Fri May 24 09:53:35 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Transportadora_ESTest extends Transportadora_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.toString();
      transportadora1.toString();
      double double0 = (-1292.740398745837);
      transportadora0.setNome((String) null);
      transportadora0.setImpostos((-1292.740398745837));
      transportadora0.clone();
      int int0 = 233;
      transportadora1.preco_transportadora2(233);
      // Undeclared exception!
      try { 
        transportadora0.equals(transportadora1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.toString();
      Transportadora.criaCodigo();
      Transportadora.setCodigo(2L);
      transportadora1.toString();
      transportadora1.setPremium(true);
      transportadora1.setMargemlucro((-541.808));
      transportadora1.toString();
      transportadora0.preco_transportadora2(1231);
      transportadora1.equals(transportadora0);
      transportadora1.formula3();
      transportadora1.preco_transportadora3(1709);
      transportadora1.toString();
      transportadora0.formula3();
      transportadora1.preco_transportadora1(2146204822);
      transportadora0.formula3();
      transportadora0.formula3();
      transportadora0.equals("(ValorBase * MargemLucroTransportadora * (1 + Imposto)) * 1,5");
      transportadora1.formula3();
      transportadora0.equals("Transportadora:: { Id: 1 Nome: Transportadora Invalida Valor da encomenda pequena: 0.0 Valor da encomenda m\u00E9dia: 0.0 Valor da encomenda grande: 0.0 Imposto: 0.0 Margem de lucro: -541.808 \u00C9 premium: true Formula atual: 0 Total lucro: 0.0}");
      transportadora1.preco_transportadora1((-1951));
      transportadora1.toString();
      transportadora0.preco_transportadora3(1709);
      transportadora0.formula3();
      transportadora0.formula2();
      transportadora0.preco_transportadora2((-2326));
      transportadora0.formula3();
      transportadora1.clone();
      transportadora1.preco_transportadora1(1709);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora3(0);
      transportadora0.getValor_grande();
      transportadora1.preco_transportadora1(0);
      transportadora0.preco_transportadora3(0);
      Transportadora transportadora2 = transportadora1.clone();
      Transportadora transportadora3 = transportadora2.clone();
      transportadora0.setImpostos(611.276701027);
      transportadora2.setPremium(true);
      transportadora1.setMargemlucro(0.0);
      transportadora3.setFormula(2211);
      transportadora2.setId(0);
      transportadora0.formula2();
      transportadora0.setMargemlucro(0.0);
      Transportadora.getCodigo();
      Transportadora.setCodigo(1L);
      transportadora0.clone();
      transportadora3.formula1();
      transportadora0.getNome();
      Transportadora transportadora4 = new Transportadora(transportadora1);
      transportadora4.setValor_grande(330.29);
      transportadora4.toString();
      transportadora3.equals(transportadora4);
      transportadora0.isPremium();
      transportadora3.getMargemlucro();
      transportadora0.getNome();
      transportadora3.formula3();
      Transportadora.setCodigo(0);
      transportadora1.formula3();
      transportadora1.preco_transportadora2(0);
      transportadora3.formula2();
      transportadora1.formula1();
      transportadora0.preco_transportadora1((-1));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("k+!am", (-1.0), (-1.0), (-1.0), 611.276701027, (-483.188228322214), true, 1581);
      transportadora0.toString();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.equals("k+!am");
      transportadora1.setMargemlucro(0.9);
      transportadora1.formula1();
      transportadora0.preco_transportadora3(1581);
      transportadora1.preco_transportadora1(1581);
      transportadora1.formula1();
      transportadora1.preco_transportadora3(1581);
      transportadora0.preco_transportadora3(1581);
      transportadora0.equals("(ValorBase * MargemLucroTransportadora * (1 + Imposto)) * 0,9");
      transportadora0.formula2();
      Transportadora.setCodigo(1581);
      transportadora1.toString();
      transportadora0.preco_transportadora3(0);
      transportadora1.toString();
      transportadora0.preco_transportadora3(0);
      transportadora0.formula3();
      transportadora1.equals(transportadora0);
      transportadora0.equals("ValorBase * (1 + MargemLucroTransportadora + Imposto) * 0,7");
      transportadora0.preco_transportadora2(1581);
      transportadora1.equals("Transportadora:: { Id: 1 Nome: k+!am Valor da encomenda pequena: -1.0 Valor da encomenda m\u00E9dia: -1.0 Valor da encomenda grande: -1.0 Imposto: 611.276701027 Margem de lucro: -483.188228322214 \u00C9 premium: true Formula atual: 1581 Total lucro: 0.0}");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setNome("");
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.setMargemlucro(1);
      transportadora0.preco_transportadora1(1);
      transportadora1.setFormula((-102));
      transportadora0.setTotalLucro((-102));
      transportadora1.getImpostos();
      Transportadora.criaCodigo();
      transportadora0.isPremium();
      transportadora1.equals((Object) null);
      transportadora1.setFormula(1150);
      transportadora1.setTotalLucro(1150);
      transportadora1.setPremium(false);
      transportadora1.getId();
      transportadora0.equals(transportadora1);
      transportadora0.getValor_pequenas();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_grande((-9.534158721381242));
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.toString();
      transportadora1.setPremium(true);
      transportadora0.setValor_pequenas(1771.225994719958);
      transportadora0.setValor_grande(1771.225994719958);
      transportadora0.getImpostos();
      transportadora0.equals("QqPcXa@j2#Z93_WzubS");
      transportadora0.equals(transportadora0);
      transportadora1.formula1();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("5#X9L5p~cOb6@aV", (-1249.0812948848431), 0.7, 0.7, (-1.0), 0.7, true, 1);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      Transportadora transportadora2 = transportadora0.clone();
      transportadora1.setFormula(1);
      transportadora1.setFormula(1);
      transportadora2.preco_transportadora1((-262));
      Transportadora.setCodigo(966L);
      transportadora0.setTotalLucro(2116.46373);
      transportadora1.formula3();
      transportadora0.formula3();
      Transportadora transportadora3 = transportadora2.clone();
      transportadora1.toString();
      transportadora3.preco_transportadora1(1453);
      transportadora3.preco_transportadora2((-1431655765));
      transportadora1.toString();
      transportadora0.equals(transportadora2);
      transportadora1.preco_transportadora2(1);
      transportadora2.preco_transportadora3(3159);
      transportadora2.formula3();
      transportadora0.preco_transportadora3(3159);
      transportadora2.toString();
      transportadora0.formula2();
      Transportadora transportadora4 = transportadora1.clone();
      transportadora4.preco_transportadora1(1);
      transportadora4.preco_transportadora3(3159);
      transportadora1.formula3();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora3(0);
      transportadora0.getValor_grande();
      transportadora1.preco_transportadora1(0);
      transportadora0.preco_transportadora3(0);
      Transportadora transportadora2 = transportadora1.clone();
      Transportadora transportadora3 = transportadora2.clone();
      transportadora0.setImpostos(611.276701027);
      transportadora2.setPremium(true);
      transportadora1.setMargemlucro(0.0);
      transportadora3.setFormula(2211);
      transportadora2.setId(0);
      transportadora0.formula2();
      transportadora0.setMargemlucro(0.0);
      Transportadora.getCodigo();
      Transportadora.setCodigo(1L);
      transportadora0.clone();
      transportadora3.formula1();
      transportadora0.getNome();
      Transportadora transportadora4 = new Transportadora(transportadora1);
      transportadora4.setImpostos((-1.0));
      transportadora4.toString();
      transportadora3.equals(transportadora4);
      transportadora0.isPremium();
      transportadora3.getMargemlucro();
      transportadora0.getNome();
      transportadora3.formula3();
      Transportadora.setCodigo(0);
      transportadora1.formula3();
      transportadora1.preco_transportadora2(0);
      transportadora3.formula2();
      transportadora1.formula1();
      transportadora1.preco_transportadora3(2211);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora.setCodigo((-2031L));
      transportadora0.setMargemlucro((-2031L));
      Transportadora.criaCodigo();
      transportadora0.setMargemlucro((-651.991));
      transportadora0.preco_transportadora3(0);
      transportadora0.getNome();
      Transportadora transportadora1 = transportadora0.clone();
      Transportadora.criaCodigo();
      transportadora1.preco_transportadora1(0);
      Transportadora.setCodigo(0L);
      transportadora1.preco_transportadora1(260);
      transportadora1.preco_transportadora2(0);
      transportadora0.isPremium();
      transportadora1.setValor_pequenas((-22.14336192654996));
      transportadora1.equals(transportadora0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.preco_transportadora3(0);
      transportadora0.getValor_grande();
      transportadora0.preco_transportadora1(0);
      transportadora0.preco_transportadora3(0);
      Transportadora transportadora1 = transportadora0.clone();
      Transportadora transportadora2 = transportadora1.clone();
      transportadora0.setImpostos(611.276701027);
      transportadora2.setFormula(2211);
      transportadora1.setId((-4799L));
      transportadora0.formula2();
      transportadora1.setMargemlucro(611.276701027);
      transportadora0.setMargemlucro(0.0);
      Transportadora.getCodigo();
      Transportadora.setCodigo((-19L));
      transportadora1.setValor_medio((-19L));
      Transportadora transportadora3 = transportadora0.clone();
      transportadora2.formula1();
      transportadora0.getNome();
      transportadora1.toString();
      transportadora1.setNome("Ar;NU6k");
      Transportadora transportadora4 = new Transportadora(transportadora0);
      transportadora4.toString();
      transportadora2.equals(transportadora4);
      transportadora3.setFormula(120);
      transportadora0.isPremium();
      transportadora2.getMargemlucro();
      transportadora0.getNome();
      transportadora2.formula3();
      Transportadora.setCodigo(0);
      transportadora3.formula3();
      transportadora0.preco_transportadora2(0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_grande((-9.534158721381242));
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.toString();
      transportadora1.setPremium(true);
      transportadora0.setValor_pequenas(1771.225994719958);
      transportadora0.setValor_grande(1771.225994719958);
      transportadora0.getImpostos();
      Transportadora transportadora2 = new Transportadora(transportadora0);
      transportadora2.setImpostos(1114.332);
      transportadora2.setPremium(true);
      transportadora0.equals(transportadora2);
      transportadora1.formula1();
      transportadora1.preco_transportadora3((-1011));
      transportadora0.formula1();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("#5TN2J\"R}DBqU%#l(/", 2.0, 2.0, 2.0, 2.0, 1.0, false, (-1291));
      transportadora0.preco_transportadora3((-1291));
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.preco_transportadora3((-1291));
      transportadora0.setPremium(true);
      transportadora1.setValor_medio(1.0);
      Transportadora.setCodigo((-1669L));
      transportadora0.preco_transportadora3(188);
      transportadora0.setImpostos((-652.3271700704436));
      transportadora1.preco_transportadora3((-678));
      transportadora1.formula3();
      transportadora1.formula2();
      transportadora0.toString();
      transportadora1.formula3();
      transportadora0.equals(transportadora1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_grande((-9.534158721381242));
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.toString();
      transportadora1.setPremium(true);
      transportadora0.setValor_pequenas(1771.225994719958);
      transportadora0.setValor_grande(1771.225994719958);
      transportadora0.getImpostos();
      transportadora0.equals("QqPcXa@j2#Z93_WzubS");
      Transportadora transportadora2 = new Transportadora(transportadora0);
      transportadora2.setFormula(1);
      transportadora0.equals(transportadora2);
      transportadora1.formula1();
      transportadora1.formula2();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora3(0);
      transportadora0.getValor_grande();
      transportadora1.preco_transportadora1(0);
      transportadora0.preco_transportadora3(0);
      Transportadora transportadora2 = transportadora1.clone();
      Transportadora transportadora3 = transportadora2.clone();
      transportadora0.setImpostos(611.276701027);
      transportadora2.setPremium(true);
      transportadora1.setMargemlucro(0.0);
      transportadora3.setFormula(2211);
      transportadora2.setId(0);
      transportadora0.formula2();
      transportadora0.setMargemlucro(0.0);
      Transportadora.getCodigo();
      Transportadora.setCodigo(1L);
      transportadora0.clone();
      transportadora3.formula1();
      transportadora0.getNome();
      Transportadora transportadora4 = new Transportadora(transportadora1);
      transportadora4.setValor_grande((-2788.262442));
      transportadora4.toString();
      transportadora3.equals(transportadora4);
      transportadora0.isPremium();
      transportadora3.getMargemlucro();
      transportadora0.getNome();
      transportadora3.formula3();
      Transportadora.setCodigo(0);
      transportadora1.formula3();
      transportadora1.preco_transportadora2(0);
      transportadora3.formula2();
      transportadora1.formula1();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora3(0);
      transportadora0.getValor_grande();
      transportadora1.preco_transportadora1(0);
      transportadora0.preco_transportadora3(0);
      Transportadora transportadora2 = transportadora1.clone();
      Transportadora transportadora3 = transportadora2.clone();
      transportadora0.setImpostos(611.276701027);
      transportadora2.setPremium(true);
      transportadora1.setMargemlucro(0.0);
      transportadora3.setFormula(2211);
      transportadora2.setId((-4799L));
      transportadora0.formula2();
      transportadora0.setMargemlucro(0.0);
      Transportadora.getCodigo();
      Transportadora.setCodigo(1L);
      transportadora2.setValor_medio(1L);
      transportadora0.clone();
      transportadora3.formula1();
      transportadora0.getNome();
      transportadora2.toString();
      Transportadora transportadora4 = new Transportadora(transportadora1);
      transportadora4.setPremium(true);
      transportadora4.toString();
      transportadora3.equals(transportadora4);
      transportadora0.isPremium();
      transportadora3.getMargemlucro();
      transportadora0.getNome();
      transportadora3.formula3();
      Transportadora.setCodigo(0);
      transportadora1.formula3();
      transportadora1.preco_transportadora2(0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora.criaCodigo();
      transportadora0.setImpostos(2L);
      transportadora0.setId((-1335L));
      transportadora0.setNome("");
      Transportadora transportadora1 = transportadora0.clone();
      transportadora0.setFormula((-92));
      transportadora0.setMargemlucro(2L);
      transportadora1.setPremium(true);
      transportadora0.preco_transportadora3(3447);
      transportadora0.setTotalLucro(0.0);
      transportadora1.setNome("");
      transportadora1.setValor_medio(2L);
      transportadora1.setImpostos(2L);
      Transportadora transportadora2 = transportadora1.clone();
      Transportadora.criaCodigo();
      transportadora1.preco_transportadora1((-1));
      transportadora2.setImpostos((-1335L));
      transportadora1.preco_transportadora3((-623));
      transportadora1.formula2();
      transportadora1.preco_transportadora1(3447);
      transportadora1.setFormula(3447);
      transportadora2.preco_transportadora3(1196);
      transportadora2.preco_transportadora2(1196);
      transportadora2.preco_transportadora1(3447);
      transportadora2.formula1();
      transportadora0.equals(transportadora2);
      transportadora1.preco_transportadora1((-1));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("{I>h/", (-22.14336192654996), (-22.14336192654996), (-22.14336192654996), 2237.542871592, (-602.6031226423042), true, (-1788));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.toString();
      transportadora1.setMargemlucro(709.256);
      Transportadora.setCodigo((-96L));
      transportadora1.setMargemlucro((-1788));
      transportadora1.setValor_medio(2256.598197);
      transportadora1.setMargemlucro((-1788));
      transportadora0.setTotalLucro(0);
      transportadora1.preco_transportadora1(0);
      transportadora1.equals(transportadora0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora3(0);
      transportadora0.getValor_grande();
      transportadora1.preco_transportadora1(0);
      transportadora0.preco_transportadora3(0);
      Transportadora transportadora2 = transportadora1.clone();
      Transportadora transportadora3 = transportadora2.clone();
      transportadora0.setImpostos(611.276701027);
      transportadora2.setPremium(true);
      transportadora1.setMargemlucro(0.0);
      transportadora3.setFormula(2211);
      transportadora2.setId((-4799L));
      transportadora0.formula2();
      transportadora0.setMargemlucro(0.0);
      Transportadora.getCodigo();
      Transportadora.setCodigo(1L);
      transportadora2.setValor_medio(1L);
      transportadora0.clone();
      transportadora3.formula1();
      transportadora0.getNome();
      transportadora2.toString();
      Transportadora transportadora4 = new Transportadora(transportadora1);
      transportadora4.toString();
      transportadora3.equals(transportadora4);
      transportadora0.isPremium();
      transportadora3.getMargemlucro();
      transportadora0.getNome();
      transportadora3.formula3();
      Transportadora.setCodigo(0);
      transportadora1.formula3();
      transportadora1.preco_transportadora2(0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora(" Imposto: ", 1.0, 845.512048432, 1.0, 845.512048432, (-1249.0812948848431), true, (-787));
      transportadora0.setPremium(true);
      transportadora0.setTotalLucro((-1249.0812948848431));
      transportadora0.setValor_grande(1.0);
      transportadora0.setPremium(true);
      transportadora0.setFormula((-787));
      transportadora0.setPremium(true);
      transportadora0.setImpostos(0.0);
      transportadora0.setImpostos(0.0);
      transportadora0.setMargemlucro(845.512048432);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora0.equals(transportadora1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.getValor_grande();
      Transportadora transportadora1 = transportadora0.clone();
      transportadora0.preco_transportadora1((-446));
      transportadora0.preco_transportadora1((-3025));
      transportadora0.setMargemlucro(0.0);
      transportadora0.setValor_pequenas(0.0);
      transportadora0.setValor_pequenas(1.0);
      transportadora0.preco_transportadora2((-1568));
      transportadora1.preco_transportadora1((-446));
      Transportadora.criaCodigo();
      transportadora0.setImpostos(0.0);
      transportadora0.setTotalLucro((-2447.138));
      transportadora0.getNome();
      transportadora0.getId();
      transportadora0.preco_transportadora1(0);
      transportadora0.preco_transportadora2((-3025));
      transportadora1.setId((-1335L));
      Transportadora.criaCodigo();
      Transportadora transportadora2 = new Transportadora(transportadora1);
      transportadora0.equals(transportadora2);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", (-1.0), 0.0, 0.0, 1382.4025708875, (-1.0), true, 1);
      Transportadora.setCodigo((-3796L));
      transportadora0.setValor_medio((-1.0));
      transportadora0.setId(0L);
      transportadora0.toString();
      transportadora0.getFormula();
      transportadora0.getFormula();
      transportadora0.setMargemlucro(17.771058);
      transportadora0.setNome("");
      transportadora0.getMargemlucro();
      transportadora0.getValor_medio();
      Transportadora.getCodigo();
      transportadora0.preco_transportadora1(1);
      Transportadora.setCodigo(0L);
      transportadora0.getImpostos();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setFormula(5);
      transportadora0.preco_transportadora2((-2566));
      transportadora0.setValor_grande(1852.829);
      transportadora0.setNome((String) null);
      transportadora0.setNome((String) null);
      transportadora0.getFormula();
      transportadora0.preco_transportadora1(5);
      transportadora0.setFormula(0);
      transportadora0.formula2();
      transportadora0.setValor_medio(0.0);
      transportadora0.formula3();
      transportadora0.getImpostos();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", (-1.0), (-1.0), 1490.734816, (-1.0), (-1.0), false, 0);
      transportadora0.setTotalLucro(0);
      transportadora0.setTotalLucro(1490.734816);
      Transportadora.setCodigo(0);
      transportadora0.preco_transportadora3((-788));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.setImpostos(-0.0);
      transportadora1.setValor_pequenas(0);
      transportadora0.getId();
      transportadora0.preco_transportadora1(0);
      transportadora1.getMargemlucro();
      transportadora0.clone();
      transportadora0.formula2();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", (-2215.206), (-2215.206), (-2215.206), (-2215.206), (-2820.4), false, 0);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.setId(0);
      transportadora1.preco_transportadora3(0);
      transportadora1.setMargemlucro((-2215.206));
      transportadora0.preco_transportadora1(408);
      transportadora0.setImpostos(0.7);
      transportadora1.setImpostos(408);
      transportadora0.preco_transportadora3(408);
      transportadora1.getNome();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", 0.9, 0.9, (-2996.07054813308), (-2996.07054813308), 1852.4506654563013, true, (-1));
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.setFormula((-1));
      transportadora0.setValor_pequenas(1720.03403993);
      transportadora0.setValor_medio(0.0);
      transportadora0.setValor_grande(663.721563173784);
      transportadora0.getFormula();
      transportadora0.equals("");
      transportadora0.setValor_medio(0.0);
      transportadora0.setImpostos((-1.0));
      transportadora0.isPremium();
      transportadora0.setImpostos(5103.53066860883);
      Transportadora.setCodigo(0L);
      Transportadora.getCodigo();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora.criaCodigo();
      transportadora0.getFormula();
      transportadora0.preco_transportadora1((-1907));
      Transportadora.criaCodigo();
      transportadora0.getFormula();
      transportadora0.setFormula(0);
      transportadora0.preco_transportadora1(2);
      transportadora0.setId(0);
      transportadora0.preco_transportadora3(0);
      Transportadora.setCodigo((-1099L));
      transportadora0.setMargemlucro((-2044.43546));
      transportadora0.setImpostos(153.357142053);
      transportadora0.setTotalLucro(0.0);
      transportadora0.preco_transportadora3(0);
      transportadora0.setNome("i]9'13jcTU2");
      transportadora0.getId();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_medio(276.34);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora0.setTotalLucro(1978.919341);
      transportadora1.setImpostos(1978.919341);
      Transportadora.criaCodigo();
      transportadora1.preco_transportadora1(0);
      transportadora1.preco_transportadora2(2);
      transportadora1.getValor_pequenas();
      Transportadora.setCodigo(0L);
      transportadora1.setValor_grande(1978.919341);
      Transportadora.setCodigo(0L);
      transportadora1.formula2();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora0.setPremium(false);
      Transportadora.criaCodigo();
      transportadora1.setFormula(1525);
      Transportadora transportadora2 = transportadora1.clone();
      transportadora2.setFormula(1525);
      transportadora1.setMargemlucro(0.0);
      transportadora2.setNome("8kC");
      Transportadora transportadora3 = transportadora0.clone();
      transportadora1.preco_transportadora2((-1));
      Transportadora.criaCodigo();
      transportadora1.setFormula((-1));
      transportadora3.setTotalLucro(1525);
      Transportadora.criaCodigo();
      transportadora3.preco_transportadora1(1686);
      transportadora0.setMargemlucro(1686);
      transportadora3.getId();
      transportadora3.getValor_grande();
      transportadora1.preco_transportadora2((-1));
      Transportadora.setCodigo((-1));
      transportadora0.setTotalLucro(408.70521);
      Transportadora transportadora4 = new Transportadora(transportadora0);
      transportadora2.equals(transportadora4);
      transportadora4.formula2();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", (-215.2), (-215.2), (-215.2), (-215.2), 0.0, true, (-3221));
      transportadora0.setTotalLucro(0.0);
      transportadora0.setNome("");
      transportadora0.toString();
      transportadora0.preco_transportadora3(0);
      transportadora0.preco_transportadora2((-1));
      transportadora0.preco_transportadora3((-2233));
      transportadora0.setValor_pequenas((-215.2));
      transportadora0.getValor_pequenas();
      transportadora0.setImpostos((-2233));
      Transportadora.criaCodigo();
      transportadora0.setValor_pequenas(0.0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", 0.0, 0.0, 0.0, 0.9, 0.0, false, (-2087));
      transportadora0.setId((-167L));
      Transportadora.setCodigo((-2087));
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.toString();
      transportadora1.setMargemlucro((-167L));
      transportadora1.getImpostos();
      transportadora1.setFormula((-2087));
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Transportadora.setCodigo(0L);
      Transportadora transportadora0 = new Transportadora("Gh>-$iD,", 1.0, 0L, 1.0, 0L, (-1.0), false, (-1));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.clone();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Transportadora.setCodigo(1L);
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.setNome("&Kr(ukBqqG99%.(");
      transportadora0.setImpostos(1L);
      transportadora1.preco_transportadora3(2);
      transportadora1.setMargemlucro(1L);
      transportadora0.setValor_medio(0.0);
      transportadora0.getImpostos();
      transportadora0.formula3();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora.setCodigo(3059L);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora0.preco_transportadora1(0);
      transportadora1.setValor_pequenas(1.0);
      transportadora1.setId((-729L));
      transportadora1.getValor_pequenas();
      transportadora1.toString();
      transportadora1.getTotalLucro();
      transportadora0.setValor_grande(1.0);
      Transportadora.setCodigo((-729L));
      Transportadora.criaCodigo();
      Transportadora.criaCodigo();
      transportadora1.getValor_medio();
      Transportadora.setCodigo(0L);
      Transportadora.criaCodigo();
      transportadora1.getId();
      transportadora0.preco_transportadora1((-4160));
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora((String) null, (-2370.493), 184.28, (-2370.493), (-1.0), 439.4144636805, false, 142);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.toString();
      Transportadora transportadora2 = transportadora0.clone();
      transportadora1.preco_transportadora3(0);
      transportadora2.setPremium(false);
      transportadora0.toString();
      Transportadora.criaCodigo();
      transportadora0.setMargemlucro(184.28);
      transportadora1.formula1();
      transportadora1.setPremium(true);
      transportadora0.getValor_pequenas();
      transportadora0.setId(142);
      transportadora0.getValor_pequenas();
      transportadora1.clone();
      transportadora0.formula3();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", (-1.0), (-1.0), (-1.0), (-1.0), (-1.0), false, 0);
      transportadora0.setTotalLucro(0);
      transportadora0.setTotalLucro((-1.0));
      transportadora0.preco_transportadora3((-788));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.setImpostos(-0.0);
      transportadora1.setValor_pequenas(0);
      transportadora0.preco_transportadora1(0);
      transportadora1.getMargemlucro();
      transportadora0.clone();
      transportadora0.formula2();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("j<K9P1e^M7A`:", (-459.50076049952), (-459.50076049952), (-459.50076049952), (-459.50076049952), (-459.50076049952), true, (-1925));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora3((-1925));
      transportadora0.setValor_grande(3793.295115899);
      transportadora1.setId(161L);
      transportadora1.getValor_grande();
      transportadora1.setImpostos((-459.50076049952));
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("l~=9A]", (-1110.1), (-1133.0573189843), (-1133.0573189843), (-1133.0573189843), (-554.456710429), true, (-1871));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora2(1);
      transportadora1.preco_transportadora3(1);
      transportadora1.setImpostos(0.0);
      transportadora0.preco_transportadora1((-260));
      transportadora0.setValor_medio((-554.456710429));
      transportadora1.setTotalLucro(1.0);
      transportadora1.setFormula((-1871));
      transportadora0.isPremium();
      transportadora0.getId();
      transportadora0.setValor_grande(1018.451447417);
      transportadora0.getNome();
      transportadora0.getValor_grande();
      transportadora1.toString();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Transportadora.criaCodigo();
      Transportadora transportadora0 = new Transportadora((String) null, 1L, 1L, 0.0, 1729.9528485784, 1L, true, (-565));
      Transportadora.criaCodigo();
      transportadora0.formula2();
      transportadora0.setValor_grande(0.9);
      transportadora0.formula3();
      transportadora0.getNome();
      transportadora0.setMargemlucro(1729.9528485784);
      transportadora0.setValor_grande((-4374.231605222527));
      transportadora0.preco_transportadora2(1404);
      transportadora0.setMargemlucro((-4374.231605222527));
      transportadora0.setTotalLucro(0.0);
      transportadora0.getMargemlucro();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setTotalLucro(309.569960290135);
      Transportadora.criaCodigo();
      transportadora0.getTotalLucro();
      transportadora0.getId();
      transportadora0.setPremium(false);
      transportadora0.preco_transportadora3((-1));
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setNome("");
      transportadora0.preco_transportadora1((-217));
      transportadora0.equals("");
      transportadora0.getNome();
      transportadora0.getFormula();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.preco_transportadora3(0);
      transportadora0.setTotalLucro((-2603.0));
      transportadora0.setNome("Q2");
      transportadora0.setPremium(true);
      transportadora0.preco_transportadora3(0);
      transportadora0.isPremium();
      transportadora0.formula3();
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.setNome("Q2");
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", (-177.363102), (-177.363102), (-1.0), (-177.363102), (-177.363102), false, 0);
      transportadora0.setFormula(0);
      transportadora0.formula3();
      transportadora0.getValor_medio();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Transportadora transportadora0 = null;
      try {
        transportadora0 = new Transportadora((Transportadora) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Transportadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", 1.0, 2295.7259097230785, 2295.7259097230785, (-775.0), (-775.0), false, (-2026));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.setImpostos(1.0);
      Transportadora.criaCodigo();
      transportadora1.getValor_medio();
      transportadora1.getNome();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = transportadora0.clone();
      transportadora0.toString();
      transportadora1.setNome(" Total lucro: ");
      transportadora0.setValor_pequenas(0.0);
      Transportadora.setCodigo(0L);
      transportadora0.getValor_grande();
      transportadora1.preco_transportadora2((-2925));
      transportadora0.getValor_medio();
      Transportadora.criaCodigo();
      transportadora1.formula2();
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Transportadora.getCodigo();
      Transportadora transportadora0 = null;
      try {
        transportadora0 = new Transportadora((Transportadora) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Transportadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.getValor_grande();
      transportadora0.setTotalLucro((-1.0));
      transportadora0.getId();
      transportadora0.setValor_pequenas(0.0);
      transportadora0.getValor_pequenas();
      transportadora0.clone();
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", 1852.471641605, 1852.471641605, 1852.471641605, 1852.471641605, 1852.471641605, true, (-2963));
      Transportadora.criaCodigo();
      transportadora0.preco_transportadora1(0);
      transportadora0.setValor_pequenas(0.0);
      transportadora0.setNome("");
      transportadora0.toString();
      transportadora0.setValor_pequenas((-2963));
      transportadora0.setValor_grande((-2695.044924));
      transportadora0.setTotalLucro((-1.0));
      transportadora0.setTotalLucro((-2963));
      transportadora0.getTotalLucro();
      transportadora0.setValor_grande(1852.471641605);
      transportadora0.preco_transportadora1((-2963));
      transportadora0.setTotalLucro((-2964.0));
      transportadora0.formula3();
      transportadora0.formula2();
      transportadora0.setImpostos(1115.1273775013585);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.getValor_medio();
      transportadora0.setTotalLucro((-1544.72466021));
      transportadora0.setTotalLucro(0.0);
      transportadora0.formula2();
      transportadora0.getNome();
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setTotalLucro((-1));
      transportadora0.setFormula((-1));
      transportadora0.setFormula(1);
      transportadora0.preco_transportadora3(1);
      transportadora0.formula3();
      transportadora0.setPremium(false);
      transportadora0.setFormula((-2018));
      transportadora0.formula1();
      transportadora0.getFormula();
      transportadora0.formula2();
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.setNome("");
      transportadora1.preco_transportadora3((-1481));
      transportadora0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("fA\"!@hEA45", 1.5, (-1679.63), 1.5, 1.5, 1401.03234, false, (-860));
      transportadora0.preco_transportadora2(1);
      transportadora0.preco_transportadora3((-79));
      transportadora0.setTotalLucro((-79));
      transportadora0.preco_transportadora2(717);
      transportadora0.getImpostos();
      transportadora0.isPremium();
      transportadora0.getValor_grande();
      transportadora0.setValor_medio(717);
      transportadora0.toString();
      transportadora0.setValor_grande((-1034.897));
      transportadora0.clone();
      Transportadora.setCodigo((-3355L));
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      Transportadora.setCodigo((-29));
      Transportadora.criaCodigo();
      transportadora1.preco_transportadora3((-29));
      transportadora1.preco_transportadora2(1);
      transportadora0.preco_transportadora3((-2091));
      transportadora1.preco_transportadora2((-6));
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("f-y/$J", 132.997477443, 132.997477443, 132.997477443, 0.0, 2144.77148354, true, 0);
      transportadora0.preco_transportadora2(0);
      transportadora0.setValor_grande(1.0);
      transportadora0.setMargemlucro(0);
      transportadora0.getValor_pequenas();
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", (-3079.129), (-3079.129), 0.0, (-2218.092045239268), (-1817.998), false, 1377);
      transportadora0.setNome("");
      transportadora0.setValor_pequenas(0.0);
      transportadora0.getFormula();
      transportadora0.toString();
      transportadora0.getFormula();
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("(ValorBase * MargemLucroTransportadora * (1 + Imposto)) * 1,5", 1232.59985051, 1232.59985051, 1.0, 0.0, 1.0, true, 0);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora1(0);
      transportadora0.getId();
      transportadora1.setMargemlucro(0);
      transportadora0.preco_transportadora3(394);
      transportadora1.getMargemlucro();
      transportadora0.preco_transportadora1(394);
      transportadora1.setMargemlucro(0.0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Transportadora.criaCodigo();
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setImpostos(1L);
      transportadora0.preco_transportadora1(220);
      transportadora0.getValor_medio();
      transportadora0.getId();
      Transportadora transportadora1 = new Transportadora();
      transportadora0.equals(transportadora1);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setFormula(0);
      transportadora0.preco_transportadora1(0);
      transportadora0.getTotalLucro();
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora(">L.cH|0a6}u%!aY", 2336.880888622, 2336.880888622, 2336.880888622, 0.0, 2336.880888622, true, 0);
      Transportadora.criaCodigo();
      transportadora0.setFormula(0);
      transportadora0.setValor_pequenas(1.0);
      transportadora0.setImpostos(3001.793213047743);
      transportadora0.preco_transportadora2(0);
      Transportadora.criaCodigo();
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora2(1274);
      transportadora1.setMargemlucro(2797.736689441648);
      transportadora1.preco_transportadora3(0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", 1.5, 1.5, 1.5, 1.5, 1.5, false, 0);
      transportadora0.formula2();
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.preco_transportadora1(435);
      transportadora0.setPremium(true);
      transportadora0.preco_transportadora2(0);
      transportadora0.getImpostos();
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setNome("hcsUI<l]zbFye8WI");
      transportadora0.toString();
      transportadora0.getValor_pequenas();
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_grande(482.1627446);
      transportadora0.setImpostos((-799.3693102775));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.getImpostos();
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Transportadora.setCodigo(0L);
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setNome("");
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.setTotalLucro((-1.0));
      transportadora1.setNome("");
      transportadora0.equals(transportadora1);
      transportadora0.setTotalLucro(1591.4209);
      transportadora0.preco_transportadora1((-1431655764));
      transportadora0.formula3();
      Transportadora transportadora2 = transportadora1.clone();
      transportadora2.setTotalLucro((-1037.87047576));
      transportadora0.preco_transportadora2((-1431655764));
      transportadora2.toString();
      transportadora2.formula2();
      transportadora2.preco_transportadora1((-1431655764));
      transportadora2.formula1();
      transportadora1.preco_transportadora3(2245);
      transportadora1.clone();
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_grande((-9.534158721381242));
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.toString();
      transportadora1.setPremium(true);
      transportadora0.setValor_pequenas(1771.225994719958);
      transportadora0.setValor_grande(1771.225994719958);
      transportadora0.getImpostos();
      Transportadora transportadora2 = new Transportadora(transportadora0);
      transportadora2.setPremium(true);
      transportadora0.equals(transportadora2);
      transportadora1.formula1();
      transportadora1.preco_transportadora3((-1011));
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setNome("");
      Transportadora transportadora1 = transportadora0.clone();
      transportadora0.preco_transportadora1(1);
      transportadora1.setFormula((-102));
      transportadora0.setTotalLucro((-102));
      transportadora1.getImpostos();
      Transportadora.criaCodigo();
      transportadora0.isPremium();
      transportadora1.equals((Object) null);
      transportadora1.setFormula(1150);
      transportadora1.setTotalLucro(1150);
      transportadora1.setPremium(false);
      transportadora1.getId();
      transportadora0.equals(transportadora1);
      transportadora0.getValor_pequenas();
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Transportadora.getCodigo();
      Transportadora transportadora0 = new Transportadora("", 1679.2629887, 1L, 1L, 0.0, 1679.2629887, true, (-107));
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.setValor_pequenas(1L);
      transportadora1.clone();
      transportadora1.getNome();
      transportadora0.equals(transportadora1);
      transportadora0.equals(transportadora1);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora((String) null, (-1.0), (-1.0), (-287.0634151), (-712.0), (-1.0), true, 2245);
      transportadora0.preco_transportadora3(0);
      transportadora0.toString();
      transportadora0.preco_transportadora1(2245);
      transportadora0.setFormula(2324);
      transportadora0.setImpostos((-287.0634151));
      transportadora0.setFormula(2245);
      transportadora0.setValor_medio((-1.0));
      transportadora0.setValor_medio((-287.0634151));
      transportadora0.setValor_pequenas((-1.0));
      transportadora0.preco_transportadora3(1);
      transportadora0.preco_transportadora1((-5));
      transportadora0.formula3();
      Transportadora.setCodigo(0L);
      transportadora0.setFormula(2245);
      transportadora0.preco_transportadora2((-4408));
      transportadora0.formula3();
      transportadora0.formula1();
      transportadora0.setTotalLucro((-429.09512265));
      transportadora0.toString();
      transportadora0.preco_transportadora2((-5));
      transportadora0.preco_transportadora1(1);
      transportadora0.setValor_grande((-183691.87932249));
      transportadora0.preco_transportadora3(1);
      transportadora0.formula1();
      transportadora0.clone();
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setTotalLucro((-2079.621086));
      transportadora0.setMargemlucro((-102.0));
      transportadora0.setImpostos((-102.0));
      transportadora0.setId((-1L));
      transportadora0.toString();
      transportadora0.toString();
      transportadora0.setNome("Transportadora:: { Id: -1 Nome: Transportadora Invalida Valor da encomenda pequena: 0.0 Valor da encomenda m\u00E9dia: 0.0 Valor da encomenda grande: 0.0 Imposto: -102.0 Margem de lucro: -102.0 \u00C9 premium: false Formula atual: 0 Total lucro: -2079.621086}");
      transportadora0.setId((-1L));
      transportadora0.equals(" Valor da encomenda pequena: ");
      transportadora0.preco_transportadora2(2);
      transportadora0.preco_transportadora1(2);
      transportadora0.formula1();
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("5#X9L5p~cOb6@aV", (-1249.0812948848431), 0.7, 0.7, (-1.0), 0.7, true, 1);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      Transportadora transportadora2 = transportadora0.clone();
      transportadora1.setFormula(1);
      transportadora1.setFormula(1);
      transportadora2.preco_transportadora1((-262));
      Transportadora.setCodigo(966L);
      transportadora0.setTotalLucro(2116.46373);
      transportadora1.formula3();
      transportadora0.formula3();
      Transportadora transportadora3 = transportadora2.clone();
      transportadora1.toString();
      transportadora3.preco_transportadora1(1453);
      transportadora3.preco_transportadora2((-1431655765));
      transportadora1.toString();
      transportadora0.equals(transportadora0);
      transportadora1.preco_transportadora2(1);
      transportadora2.preco_transportadora3(3159);
      transportadora2.formula3();
      transportadora0.preco_transportadora3(3159);
      transportadora2.toString();
      transportadora0.formula2();
      Transportadora transportadora4 = transportadora1.clone();
      transportadora4.preco_transportadora1(1);
      transportadora4.preco_transportadora3(3159);
      transportadora1.formula3();
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", 2387.1899766, 2387.1899766, 2387.1899766, 3910.5, 2387.1899766, true, 3448);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.setValor_medio(3448);
      transportadora0.setFormula((-135));
      transportadora1.formula3();
      transportadora1.setNome("(ValorBase * MargemLucroTransportadora * (1 + Imposto)) * 1,5");
      transportadora0.preco_transportadora3(3448);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_grande((-9.534158721381242));
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.toString();
      transportadora1.setPremium(true);
      transportadora0.setValor_pequenas(1771.225994719958);
      transportadora0.setValor_grande(1771.225994719958);
      transportadora0.getImpostos();
      Transportadora transportadora2 = new Transportadora(transportadora0);
      transportadora0.equals(transportadora2);
      transportadora1.formula1();
      transportadora1.equals(transportadora0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_grande(0.0);
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.toString();
      transportadora1.setPremium(true);
      transportadora0.setValor_pequenas(1771.225994719958);
      transportadora0.setValor_grande(1771.225994719958);
      transportadora0.getImpostos();
      transportadora0.equals("QqPcXa@j2#Z93_WzubS");
      Transportadora transportadora2 = new Transportadora(" \u00C9 premium: ", (-625.91875), 1.5, 0.0, (-625.91875), 0.0, true, (-1011));
      transportadora0.equals(transportadora2);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Transportadora.criaCodigo();
      Transportadora transportadora0 = new Transportadora();
      transportadora0.setValor_grande(1L);
      Transportadora transportadora1 = transportadora0.clone();
      transportadora1.setValor_grande(1.0);
      transportadora1.setMargemlucro(1.0);
      transportadora0.setValor_pequenas(0.0);
      transportadora0.preco_transportadora3(5);
      transportadora0.setNome(" Nome: ");
      transportadora0.preco_transportadora2(5);
      transportadora0.setFormula(5);
      transportadora0.formula1();
      transportadora1.setId(1L);
      transportadora1.getMargemlucro();
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora();
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora0.getValor_grande();
      Transportadora transportadora2 = transportadora1.clone();
      Transportadora transportadora3 = transportadora2.clone();
      transportadora0.setImpostos(611.276701027);
      transportadora2.setPremium(true);
      transportadora3.setFormula(2211);
      transportadora2.setId((-4799L));
      transportadora0.formula2();
      Transportadora.getCodigo();
      Transportadora.setCodigo((-19L));
      transportadora2.setValor_medio((-19L));
      Transportadora transportadora4 = transportadora0.clone();
      transportadora3.formula1();
      transportadora0.getNome();
      transportadora2.toString();
      Transportadora transportadora5 = new Transportadora(transportadora1);
      transportadora5.toString();
      transportadora3.equals(transportadora5);
      transportadora0.isPremium();
      transportadora3.getMargemlucro();
      transportadora0.getNome();
      transportadora3.formula3();
      transportadora4.formula3();
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      Transportadora transportadora0 = new Transportadora("", 1.0, 2.0, (-0.36085008795457707), 1.0, 0.0, false, 0);
      Transportadora transportadora1 = new Transportadora(transportadora0);
      transportadora1.preco_transportadora1(0);
      transportadora1.preco_transportadora1(0);
      Transportadora transportadora2 = transportadora1.clone();
      transportadora1.setTotalLucro(1.0);
      transportadora2.toString();
      Transportadora transportadora3 = transportadora1.clone();
      transportadora1.preco_transportadora2(0);
      Transportadora.setCodigo(24L);
      Transportadora transportadora4 = transportadora0.clone();
      transportadora4.preco_transportadora1(0);
      transportadora1.getMargemlucro();
      transportadora2.preco_transportadora2(5717);
      transportadora1.preco_transportadora2(5717);
      transportadora1.setTotalLucro(681.5772406268217);
      Transportadora.getCodigo();
      transportadora0.getValor_grande();
      transportadora1.getValor_medio();
      transportadora3.equals("Transportadora:: { Id: 1 Nome:  Valor da encomenda pequena: 1.0 Valor da encomenda m\u00E9dia: 2.0 Valor da encomenda grande: -0.36085008795457707 Imposto: 1.0 Margem de lucro: 0.0 \u00C9 premium: false Formula atual: 0 Total lucro: 0.0}");
      transportadora2.formula1();
      transportadora0.setValor_medio(0.0);
      transportadora1.getFormula();
      transportadora1.clone();
      transportadora1.setImpostos(0.0);
      assertEquals(682.0720505036852, transportadora1.getTotalLucro(), 0.01);
  }
}
